### ISSUE TITLE
Explorer not working!

### ISSUE THREAD

**Issue by faridhassani** [scqubits/scqubits#100]
### Documentation check
In the examples provided by the documentation the old way of making interactions and creating parameter sweeps was used to run the Explorer. 
-It is not mentioned that the Explorer is not compatible with the new version yet.

### Describe the bug
The explorer fails to run with the new way of creating parameter sweeps. When I set up the parameter sweep with the new way the Explorer spits out the following error"'ParameterSweep' object has no attribute 'param_name'". The "param_name" attribute was part of the old parameter sweep settings.

### To Reproduce
Used the examples provided by the document to implement the add_interaction followed by a parameter sweep, and then passed the sweep to Explorer.

fluxQ1 = qubit.Fluxonium(
    EJ =3,
    EC =.57,
    EL =1.6,
    flux =0,
    cutoff =110,
    truncated_dim=20
)
osc = qubit.Oscillator(
    E_osc=10.4841,
    truncated_dim=5
)

hilbertspace = qubit.HilbertSpace([fluxQ1, osc])

g_strength=0.10675

operator1 = fluxQ1.n_operator()
operator2 = osc.creation_operator() + osc.annihilation_operator()

hilbertspace.add_interaction(
    g=g_strength,
    op1=(operator1, fluxQ1),
    op2=(operator2, osc),
    add_hc=True
)

pname1 = 'flux'
flux_vals = np.linspace(-1.0, 1.0, 501)

def update_hilbertspace(flux):  # function that defines how Hilbert space components are updated
    fluxQ1.flux = flux

paramvals_by_name = {pname1: flux_vals}

sweep = ParameterSweep(
    hilbertspace=hilbertspace,
    paramvals_by_name=paramvals_by_name,
    update_hilbertspace=update_hilbertspace,
    evals_count=20
)

explorer = Explorer(
     sweep=sweep,
     evals_count=10
 )
explorer.interact()

### OS and version used (please complete the following information):
 - OS: Windows 10
 - scqubits version 2

**Comment by jkochNU** [comment]
This is correct. `Explorer` continues to work with the old-style `ParameterSweep` but has not been updated to cooperate with the new interface. I think there are general questions here for the future where we want to go with `Explorer` -- whether it is something to be phased out, something being used/useful, or something that we would want to extend. (Comments welcome.)

For now, a comment needs to be inserted into the documentation that clarifies the current status to avoid confusion.

**Comment by faridhassani** [comment]
Explorer is mostly useful in the discussions with colleges where one wants to show the result of a change in the parameters (in our case mostly external flux). I personally make a specific notebook for each device and I mostly call explorer in the notebook to make it easy for everyone to see the details of the device and play around. The mostly used panel in explorer in our group was the potential and wavefunctions where you can sweep the external flux and see how the states configuration change. I was just using the new GUI implemented and this panel is also accessible there. The good thing about the explorer is that it is specific to a device and one can include composite systems (qubits coupled to resonators) in explorer while the GUI is a general tool.

**Comment by jkochNU** [comment]
@faridhassani This should be cured with https://github.com/scqubits/scqubits/commit/0ea103ce3db0dc416eda7918332b8294baefbe19 .
