### ISSUE TITLE
Plotting the spectrum in ParameterSweep with plot_transitions despite the ground state not corresponding to the bare ground state

### ISSUE THREAD

**Issue by dkweiss31** [scqubits/scqubits#103]
In some cases when plotting a `ParameterSweep` object `sweep` using `sweep[:].plot_transitions()` the spectrum disappears if there is no dressed state with bare labels `(0,0,...)`. It might be useful to just plot the spectrum as grayscale there, as opposed to the spectrum pausing and continuing abruptly. An example is below
<img width="820" alt="image" src="https://user-images.githubusercontent.com/32396142/116169437-4ec3ee00-a6ca-11eb-981e-7eea4c79cc5e.png">

**Comment by jkochNU** [comment]
Tentative fix by https://github.com/scqubits/scqubits/commit/43538b0d84e06b1331d93fa38b1421beeca01a68.
@dkweiss31 Please confirm.

**Comment by dkweiss31** [comment]
Indeed I believe it is fixed! Many thanks

**Comment by jkochNU** [comment]
Fixed by treating ground state as special case. Issue will remain for other initial states though.

**Comment by jkochNU** [comment]
The "fix" to the above problem fails and can give erroneous results in ultrastrong coupling when the ground states is not derived from (0,0,..,0).

**Comment by jkochNU** [comment]
This should now be addressed by https://github.com/scqubits/scqubits/commit/625e20413be02adb0fe03c8386fbec422828f9db. Documentation about additional options when calling `plot_transitions` has been added to the RTD master.
