### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by Timmenke** [scqubits/scqubits#105]
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [x ] I have checked the API documentation.
 - [ x] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug
I just installed scqubits-1.2.1 and can't import it in python (neither jupyter nor command line). The first issue was that I needed to do `from ipywidgets import widgets` before the `import scqubits as scq` statement. After I resolved that, I still couldn't load the package and received the following error:
`~/anaconda3/lib/python3.6/site-packages/scqubits/ui/gui.py in <module>()`
`     46 `
`     47 import scqubits as scq`
`---> 48 import scqubits.utils.misc as utils`
`     49 `
`     50 from scqubits.core.qubit_base import QubitBaseClass`
`AttributeError: module 'scqubits' has no attribute 'utils'`

### Expected behavior
I would have expected scqubits to load after installation.

### OS and version used (please complete the following information):
 - OS: macOS 10.15.7
 - scqubits version 1.2.1
 - Python version 3.6.5 (Anaconda)

### Additional context
Thanks for the great package! It works well in Binder, just not on my own machine.

**Comment by Timmenke** [comment]
I got scqubits to load after commenting out most of the gui.py file (which probably disabled some functionality but I don't need the GUI for what I want to try). See attached.
[gui.py.zip](https://github.com/scqubits/scqubits/files/6709725/gui.py.zip)

**Comment by jkochNU** [comment]
Thank you for filing your issue. We will be looking into it. The problem is puzzling since that release passed all pytests with Python 3.6 on macOS (not sure which macOS version, though - this ran via Azure).

**Comment by Timmenke** [comment]
Thanks for the prompt reply! It's possible that this is a rare case related to my combination of Anaconda version, macOS version etc. Just wanted to flag it in case others also experience it. I got everything that I needed to work after all (just not the GUI, which is not crucial for me). Thanks again for the great package!

**Comment by jkochNU** [comment]
It's quite possible that this is a rare case (at least it is the first we encounter, with a several people in our group using macOS and anaconda as well). Would be good to understand the origin, so we can minimize rare cases. If you would not mind: could you please post the result from `conda list` so we have an even better understanding of your environment? Thanks!

**Comment by Timmenke** [comment]
Yes of course, here we go:
-------
# Name                    Version                   Build  Channel
_anaconda_depends         5.2.0                    py36_3  
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0  
aiocontextvars            0.2.2                    pypi_0    pypi
alabaster                 0.7.10           py36h174008c_0  
anaconda                  custom                   py36_1  
anaconda-client           1.6.14                   py36_0  
anaconda-navigator        1.8.7                    py36_0  
anaconda-project          0.8.2            py36h9ee5d53_0  
antlr-python-runtime      4.7.2                 py36_1000    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.0            py36hf537a9a_0  
appscript                 1.0.1            py36h9e71e49_1  
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.3                    py36_0  
astropy                   3.0.2            py36h917ab60_1  
attrs                     18.1.0                   py36_0  
autograd                  1.3                      pypi_0    pypi
babel                     2.5.3                    py36_0  
backcall                  0.1.0                    py36_0  
backports                 1.0              py36ha3c1827_1  
backports.functools_lru_cache 1.6.1                      py_0  
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.6.0            py36h72d3c9f_1  
bitarray                  0.8.1            py36h1de35cc_1  
bkcharts                  0.2              py36h073222e_0  
blas                      1.0                         mkl  
blaze                     0.11.3           py36h02e7a37_0  
bleach                    2.1.3                    py36_0  
blosc                     1.14.3               hd9629dc_0  
bokeh                     0.12.16                  py36_0  
boto                      2.48.0           py36hdbc59ac_1  
bottleneck                1.2.1            py36hbd380ad_0  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py36h79c6626_1    conda-forge
cffi                      1.11.5           py36h342bebf_0  
chardet                   3.0.4            py36h96c241c_1  
click                     6.7              py36hec950be_0  
cloudpickle               0.5.3                    py36_0  
clyent                    1.2.2            py36hae3ad88_0  
colorama                  0.3.9            py36hd29a30c_0  
conda                     4.9.2            py36h79c6626_0    conda-forge
conda-build               3.10.5                   py36_0  
conda-package-handling    1.6.0            py36h1de35cc_0  
conda-verify              3.4.2                      py_1  
contextlib2               0.5.5            py36hd66e5e7_0  
contextvars               2.4                      pypi_0    pypi
cryptography              2.2.2            py36h1de35cc_0  
curl                      7.60.0               ha441bb4_0  
cycler                    0.10.0           py36hfc81398_0  
cython                    0.29.16                  pypi_0    pypi
cytoolz                   0.9.0.1          py36h1de35cc_0  
dask                      0.17.5                   py36_0  
dask-core                 0.17.5                   py36_0  
datashape                 0.5.4            py36hfb22df8_0  
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py36_0  
distributed               1.21.8                   py36_0  
docutils                  0.14             py36hbfde631_0  
entrypoints               0.2.3            py36hd81d71f_2  
et_xmlfile                1.0.1            py36h1315bdc_0  
expat                     2.2.5                hb8e80ba_0  
fastcache                 1.0.2            py36h1de35cc_2  
filelock                  3.0.4                    py36_0  
flask                     1.0.2                    py36_1  
flask-cors                3.0.4                    py36_0  
forestopenfermion         0.0.5                    pypi_0    pypi
freetype                  2.8                  h12048fb_1  
funcsigs                  1.0.2                    pypi_0    pypi
future                    0.18.2                   py36_0  
gdscad                    0.4.5                    pypi_0    pypi
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.3.0            py36h1de35cc_0  
glib                      2.56.1               h35bc53a_0  
glob2                     0.6              py36h94c9186_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py36hf9c35bd_2  
greenlet                  0.4.13           py36h1de35cc_0  
h5py                      2.9.0                    pypi_0    pypi
hdf5                      1.10.2               hfa1e0ec_1  
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h4b95b61_1  
idna                      2.6              py36h8628d0a_1  
imageio                   2.3.0                    py36_0  
imagesize                 1.0.0                    py36_0  
immutables                0.15                     pypi_0    pypi
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py36_0  
ipython                   6.4.0                    py36_0  
ipython_genutils          0.2.0            py36h241746c_0  
ipywidgets                7.2.1                    py36_0  
isort                     4.3.4                    py36_0  
itsdangerous              0.24             py36h49fbb8d_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4                      py36_0  
jedi                      0.12.0                   py36_1  
jinja2                    2.10             py36hd36f9c5_0  
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py36hb385e00_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0            py36hccf5b1c_1  
jupyter_core              4.4.0            py36h79cf704_0  
jupyterlab                0.32.1                   py36_0  
jupyterlab_launcher       0.10.5                   py36_0  
kiwisolver                1.0.1            py36h792292d_0  
lazy-object-proxy         1.3.1            py36h2fbbe47_0  
libcurl                   7.60.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                hcb84e12_1  
libxml2                   2.9.8                hab757c2_1  
libxslt                   1.1.32               hb819dd2_0  
llvmlite                  0.23.1           py36hc454e04_0  
locket                    0.2.0            py36hca03003_1  
loguru                    0.5.3                    pypi_0    pypi
lxml                      4.2.1            py36h7166777_0  
lzo                       2.10                 h362108e_2  
markupsafe                1.0              py36h3a1e703_1  
marshmallow               2.19.5                   pypi_0    pypi
marshmallow-polyfield     3.2                      pypi_0    pypi
matplotlib                3.3.4                    pypi_0    pypi
mccabe                    0.6.1            py36hdaeb55d_0  
mistune                   0.8.3            py36h1de35cc_1  
mkl                       2018.0.2                      1  
mkl-service               1.1.2            py36h7ea6df4_4  
mkl_fft                   1.0.1            py36h917ab60_0  
mkl_random                1.0.1            py36h78cc56f_0  
mock                      3.0.5                    pypi_0    pypi
more-itertools            4.1.0                    py36_0  
mpc                       1.0.3                h7a72875_5  
mpfr                      3.1.5                h711e7fd_2  
mpmath                    1.0.0            py36hf1b8295_2  
msgpack                   0.5.6                    pypi_0    pypi
msgpack-python            0.5.6            py36h04f5b5a_0  
multipledispatch          0.5.0                    py36_0  
navigator-updater         0.2.1                    py36_0  
nbconvert                 5.3.1            py36h810822e_0  
nbformat                  4.4.0            py36h827af21_0  
ncurses                   6.1                  h0a44026_0  
networkx                  2.1                      py36_0  
nltk                      3.3.0                    py36_0  
nose                      1.3.7            py36h73fae2b_2  
notebook                  5.5.0                    py36_0  
numba                     0.38.0           py36h1702cab_0  
numexpr                   2.6.5            py36h057f876_0  
numpy                     1.19.5                   pypi_0    pypi
numpydoc                  0.8.0                    py36_0  
odo                       0.5.1            py36hc1af34a_0  
olefile                   0.45.1                   py36_0  
opencv-python             4.1.0.25                 pypi_0    pypi
openfermion               0.9.0                    pypi_0    pypi
openfermionpsi4           0.4                      pypi_0    pypi
openfermionpyscf          0.4                      pypi_0    pypi
openpyxl                  2.5.3                    py36_0  
openssl                   1.0.2u               h0b31af3_0    conda-forge
packaging                 17.1                     py36_0  
pandas                    0.23.0           py36h1702cab_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py36h3b0b094_1  
parso                     0.2.0                    py36_0  
partd                     0.3.8            py36hf5c4cb8_0  
path.py                   11.0.1                   py36_0  
pathlib2                  2.3.2                    py36_0  
patsy                     0.5.0                    py36_0  
pcre                      8.42                 h378b8a2_0  
pennylane                 0.10.0                   pypi_0    pypi
pennylane-qchem           0.10.0                   pypi_0    pypi
pep8                      1.7.1                    py36_0  
pexpect                   4.5.0                    py36_0  
pickleshare               0.7.4            py36hf512f8e_0  
pillow                    8.1.2                    pypi_0    pypi
pip                       21.0.1                   pypi_0    pypi
pkginfo                   1.4.2                    py36_1  
pluggy                    0.6.0            py36hb1d0581_0  
ply                       3.11                     py36_0  
prompt_toolkit            1.0.15           py36haeda067_0  
psutil                    5.4.5            py36h1de35cc_0  
ptyprocess                0.5.2            py36he6521c3_0  
pubchempy                 1.0.4                    pypi_0    pypi
py                        1.5.3                    py36_0  
pyaml                     20.4.0                   pypi_0    pypi
pybind11                  2.4.3            py36h04f5b5a_0  
pycodestyle               2.4.0                    py36_0  
pycosat                   0.6.3            py36hee92d8f_0  
pycparser                 2.18             py36h724b2fc_1  
pycrypto                  2.6.1            py36h1de35cc_8  
pycurl                    7.43.0.1         py36hdbc3d79_0  
pyflakes                  1.6.0            py36hea45e83_0  
pygments                  2.2.0            py36h240cd3f_0  
pylint                    1.8.4                    py36_0  
pyodbc                    4.0.23           py36h0a44026_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.0            py36hb281f35_0  
pyqt                      5.9.2            py36h11d3b92_0  
pyquil                    2.9.1                      py_0    conda-forge
pyscf                     1.7.1                    pypi_0    pypi
pysocks                   1.6.8                    py36_0  
pytables                  3.4.3            py36h5ca999c_2  
pytest                    3.5.1                    py36_0  
pytest-arraydiff          0.2                      py36_0  
pytest-astropy            0.3.0                    py36_0  
pytest-doctestplus        0.1.3                    py36_0  
pytest-openfiles          0.3.0                    py36_0  
pytest-remotedata         0.2.1                    py36_0  
python                    3.6.5                hc167b69_1  
python-dateutil           2.7.3                    py36_0  
python-rapidjson          0.6.3            py36h0a44026_0  
python.app                2                        py36_8  
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2018.4                   py36_0  
pywavelets                0.5.2            py36h2710a04_0  
pyyaml                    3.12             py36h2ba1e63_1  
pyzmq                     17.0.0           py36h1de35cc_1  
qt                        5.9.5                h02808f3_0  
qtawesome                 0.4.4            py36h468c6fb_0  
qtconsole                 4.3.1            py36hd96c0ff_0  
qtpy                      1.4.1                    py36_0  
quantum-grove             1.7.0                    pypi_0    pypi
qutip                     4.3.1                    pypi_0    pypi
readline                  7.0                  hc1231fa_4  
requests                  2.18.4           py36h4516966_1  
rope                      0.10.7           py36h68959ac_0  
rpcq                      2.7.1                      py_0    conda-forge
ruamel.yaml               0.16.5           py36h1de35cc_1  
ruamel.yaml.clib          0.2.0            py36h1de35cc_0  
ruamel_yaml               0.15.35          py36h1de35cc_1  
scikit-image              0.13.1           py36h1de35cc_1  
scikit-learn              0.24.2                   pypi_0    pypi
scikit-optimize           0.8.1                    pypi_0    pypi
scipy                     0.19.0                   pypi_0    pypi
scqubits                  2.1.0                    pypi_0    pypi
seaborn                   0.8.1            py36h595ecd9_0  
semantic-version          2.6.0                    pypi_0    pypi
send2trash                1.5.0                    py36_0  
setuptools                39.1.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
simpy                     4.0.1                    pypi_0    pypi
singledispatch            3.4.0.3          py36hf20db9d_0  
sip                       4.19.8           py36h0a44026_0  
six                       1.11.0           py36h0e22d5e_1  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.2.1            py36h6c7b616_0  
sortedcollections         0.6.1                    py36_0  
sortedcontainers          1.5.10                   py36_0  
sphinx                    1.7.4                    py36_0  
sphinxcontrib             1.0              py36h9364dc8_1  
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1  
spyder                    3.2.8                    py36_0  
sqlalchemy                1.2.7            py36hb402a30_0  
sqlite                    3.23.1               hf1716c9_0  
statsmodels               0.9.0            py36h917ab60_0  
sympy                     1.1.1            py36h7f3cf04_0  
tbb                       2019.8               h04f5b5a_0  
tbb4py                    2019.8           py36h04f5b5a_0  
tblib                     1.3.2            py36hda67792_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h625a49b_0  
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.7                h35a86e2_3  
toml                      0.10.1                   pypi_0    pypi
toolz                     0.9.0                    py36_0  
tornado                   5.0.2                    py36_0  
tqdm                      4.42.0                     py_0  
traitlets                 4.3.2            py36h65bd3ce_0  
typing                    3.6.4                    py36_0  
unicodecsv                0.14.1           py36he531d66_0  
unixodbc                  2.3.6                h3efe00b_0  
urllib3                   1.22             py36h68b9469_0  
wcwidth                   0.1.7            py36h8c6ec74_0  
webencodings              0.5.1            py36h3b9701d_1  
werkzeug                  0.14.1                   py36_0  
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.2.1                    py36_0  
wrapt                     1.10.11          py36hc29e774_0  
xlrd                      1.1.0            py36h336f4a2_1  
xlsxwriter                1.0.4                    py36_0  
xlwings                   0.11.8                   py36_0  
xlwt                      1.2.0            py36h5ad1178_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h378b8a2_0  
zict                      0.1.3            py36h71da714_0  
zlib                      1.2.11               hf3cbc9b_2

**Comment by petergthatsme** [comment]
could it be that you are installing scqubits via (conda's version of) `pip`? Based on anaconda's docs that seems to be discouraged and they claim it can lead to problems. 

I can reproduce the wonky gui related widgets errors when i do that on my machine... (i.e.  when install scqubits via pip that conda sets up.... on the other hand when i install scqubits with `conda install -c conda-forge scqubits`, everything works fine):

```
(test4) pgroszko@laptop7~$ python
Python 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scqubits as scq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pgroszko/anaconda3/envs/test4/lib/python3.8/site-packages/scqubits/__init__.py", line 51, in <module>
    from scqubits.ui.gui import GUI
  File "/home/pgroszko/anaconda3/envs/test4/lib/python3.8/site-packages/scqubits/ui/gui.py", line 53, in <module>
    class GUI:
  File "/home/pgroszko/anaconda3/envs/test4/lib/python3.8/site-packages/scqubits/ui/gui.py", line 671, in GUI
    def energy_scan_interactive(self) -> widgets.interactive:
NameError: name 'widgets' is not defined
```

Maybe the first thing to try (in case you haven't already) would be to: 
(1) update your conda distribution 
(2) create a clean conda environment
(3) install scqubits via `conda install -c conda-forge scqubits` (this is the crucial step - do not use pip that anaconda sets up)

If that doesn't work, perhaps setting a conda environement with a newer python version would also by worthwhile. 

(Finally, the scqubits that you are getting should not be 1.2.1, but instead 2.1)

**Comment by jkochNU** [comment]
Thanks, @petergthatsme !  
I realize that both our README and documentation say something along the lines of "Alternatively, you can install scqubits via pip." Should I insert a parenthetical remark about `pip` install being discouraged while using a `conda` environment?

**Comment by Timmenke** [comment]
Thanks a lot for the answers and for reproducing the issue. This is extremely helpful. I will upgrade my anaconda distribution accordingly (I have been having issues with the `conda install` command, which is why I used `pip`). From my user perspective, a parenthetical note about not using `pip` within a `conda` environment would be great. That concludes the issue, thanks so much!

**Comment by petergthatsme** [comment]
Thanks for the follow up @Timmenke.
Yes, I agree with both of you, some mention of this should be in our docs, which I will add.
