### ISSUE TITLE
The dispersion curve that scqubits generates does not match the documentation. [Bug report]

### ISSUE THREAD

**Issue by saipavanc** [scqubits/scqubits#111]
I tried to regenerate the dispersion plot given in the documentation at [https://scqubits.readthedocs.io/en/latest/guide/ipynb/basics.html](https://scqubits.readthedocs.io/en/latest/guide/ipynb/basics.html) for Transmon. But, the resultant plot is not what is what is expected. It does not even generate three plots for the levels given as parameters. The axis labels are also not visible, I also checked the same behavior when I called the subroutine through a different code, which I am sure was working fine a few days ago.  
![2021-08-02_17-18](https://user-images.githubusercontent.com/79005467/127941014-f0c812f2-50dc-47e0-9f8e-41de6449f31d.png)

### OS and version used (please complete the following information):
 - Arch Linux - 5.10.52-1-lts 
 - scqubits version [2.2.1]
 - Python version [3.9.6]

### Additional context
Any additional information you would like to provide to aid us.

**Comment by jkochNU** [comment]
Looking into this. (Probably unrelated, but I should point out that Python 3.9 is not yet officially supported.)

**Comment by jkochNU** [comment]
Output on my end differs from the above (generated with the current master):
![image](https://user-images.githubusercontent.com/19193849/127949439-e28187f1-fcf9-44ef-bf5f-f7a83848aee6.png)

**Comment by jkochNU** [comment]
Fixed with https://github.com/scqubits/scqubits/commit/85483bcb12a2c8da33aefe5cdcd80218e808f32a
