### ISSUE TITLE
[documentation] Sign inconsistency for inductive energy between Transmon and TunableTransmon?

### ISSUE THREAD

**Issue by loganbvh** [scqubits/scqubits#117]
In the online documentation, I believe the sign of the inductive part of the Hamiltonian for the tunable transmon is wrong (inconsistent with the code and with the documentation for non-tunable transmon).

`Transmon`:
![image](https://user-images.githubusercontent.com/20325010/150220243-1024fc16-8efa-4dea-aa82-71bc902c1d38.png)

`TunableTransmon`:
![image](https://user-images.githubusercontent.com/20325010/150220344-f12a6feb-141e-4c61-8e4c-ac157c91f81c.png)

Implementation for `Transmon`...
https://github.com/scqubits/scqubits/blob/e59e8588bf90103efcea6ee72381edb0e45630c5/scqubits/core/transmon.py#L150-L151

...which is inherited by `TunableTransmon`:
https://github.com/scqubits/scqubits/blob/e59e8588bf90103efcea6ee72381edb0e45630c5/scqubits/core/transmon.py#L436-L443

**Comment by jkochNU** [comment]
Thank you for taking the time to report and post this, @loganbvh. 
I suspect that, technically speaking, the sign in question is merely a gauge choice without consequences. Consider the map: 
|n>  ->  |n>   for n odd,
|n>  -> -|n>  for n even

In any case, I agree that  consistency in that sign choice is valuable to avoid confusion, so I have made changes to the docstring in `TunableTransmon` (pulled for API docs generation) and the text in the User Guide/Qubits section. This has been pushed to scqubits/master and scqubits-doc/rtd and changes should be reflected in the online documentation. If you have a moment, please check and confirm before I close the issue.

**Comment by loganbvh** [comment]
Thanks for the quick response and fix! User Guide/Qubits looks consistent now, but I think that the docstrings for `Transmon` and `TunableTransmon` (which had the same sign in the previous commit, in contrast with User Guide/Qubits) are now inconsistent:

https://github.com/scqubits/scqubits/blob/dfe5693278173a2c757e78c8d964f36ec4ccf142/scqubits/core/transmon.py#L45-L47

https://github.com/scqubits/scqubits/blob/dfe5693278173a2c757e78c8d964f36ec4ccf142/scqubits/core/transmon.py#L374-L380

**Comment by jkochNU** [comment]
@loganbvh Should be fine now, but if there's anything left, please reopen. Thanks again for your time and help to improve this!
