### ISSUE TITLE
[Bug report] Effective noise channels incorrect for FullZeroPi

### ISSUE THREAD

**Issue by 99elam** [scqubits/scqubits#118]
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [x] I have checked the API documentation.
 - [ ] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug
Please provide a concise description of what the bug is.
When printing the effective noise channels for the FullZeroPi qubit, three of the noise channels are concatenated ('tphi_1_over_f_fluxt1_bias_flux_linet1_inductive').

### Expected behavior
To minimize misunderstandings, please state briefly what you expected to happen.
I expect each of these three noise channels to be separate in the list.

### To Reproduce
If not clear from your description above, please provide the steps to reproduce the behavior:
for i in scq.FullZeroPi.effective_noise_channels():
    print(i)

### OS and version used (please complete the following information):
 - OS: Windows 10
 - scqubits version: 2.2.2
 - Python version: 3.7

### Additional context
Any additional information you would like to provide to aid us.

**Comment by jkochNU** [comment]
@99elam Can you confirm this issue may now be closed?

**Comment by 99elam** [comment]
Confirmed!
