### ISSUE TITLE
[Bug report] t_exp incorrect in the docs

### ISSUE THREAD

**Issue by 99elam** [scqubits/scqubits#119]
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [ ] I have checked the API documentation.
 - [ ] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug
Please provide a concise description of what the bug is.

t_exp shows a default value of 1 second in the docs while the actual default setting is different. 

### Expected behavior
To minimize misunderstandings, please state briefly what you expected to happen.

The default value of t_exp should be the same as what is in the docs (1ms).

### To Reproduce
If not clear from your description above, please provide the steps to reproduce the behavior:

### OS and version used (please complete the following information):
 - OS: Windows
 - scqubits version 2.2
 - Python version 3.7

### Additional context
Any additional information you would like to provide to aid us.

**Comment by petergthatsme** [comment]
fixed now, thanks for posting.
