### ISSUE TITLE
[Bug report] Flux Qubit missing flux noise

### ISSUE THREAD

**Issue by 99elam** [scqubits/scqubits#120]
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [ ] I have checked the API documentation.
 - [ ] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug
Please provide a concise description of what the bug is.

The FluxQubit only seems to have effective noise channels from critical current noise, and not from flux noise. 

### Expected behavior
To minimize misunderstandings, please state briefly what you expected to happen.

I expected tphi_1_over_f_flux to be returned in the effective_noise_channels list from the FluxQubit.

### To Reproduce
If not clear from your description above, please provide the steps to reproduce the behavior:

### OS and version used (please complete the following information):
 - OS: Windows
 - scqubits version 2.2
 - Python version 3.7

### Additional context
Any additional information you would like to provide to aid us.

**Comment by jkochNU** [comment]
@petergthatsme Was there a reason/specific problem that led to this omission?

**Comment by petergthatsme** [comment]
1/f flux noise has now been implemented in a `FluxQubit` in https://github.com/scqubits/scqubits/issues/185.
