### ISSUE TITLE
[Bug report] Deprecation namespace warnings for `scipy.sparse`

### ISSUE THREAD

**Issue by nikosavola** [scqubits/scqubits#123]
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [x] I have checked the API documentation.
 - [x] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug

Deprecation warnings are raised by scipy for two imports: `csc_matrix` and `dia_matrix`.

```
  /usr/local/lib/python3.9/site-packages/scqubits/core/zeropi.py:24: DeprecationWarning: Please use `csc_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csc` namespace is deprecated.
    from scipy.sparse.csc import csc_matrix
  /usr/local/lib/python3.9/site-packages/scqubits/core/zeropi.py:25: DeprecationWarning: Please use `dia_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.dia` namespace is deprecated.
    from scipy.sparse.dia import dia_matrix
```
Change appears to have been made in scipy 1.8.0, see https://github.com/scipy/scipy/commit/f84b8039ac9cc9cee1144958d05db750ac8e9dee

### Expected behavior
No warnings should be outputted.

### To Reproduce
import the file `scqubits/core/cos2phi_qubit.py`

### OS and version used (please complete the following information):
 - OS: Linux
 - scqubits version: 2.2.2
 - Python version: 3.9

### Additional context
Easy to fix by importing from suggested namespace.

**Comment by jkochNU** [comment]
Thanks for the report and the associated pull request. There's a broader question here: what is the range of scipy versions we are actually supporting at this point. The `requirements.txt` entry may not be accurate anymore. Pinning to the latest scipy version should be avoided for several reasons, including questions about Python version support (not critical if we go through with dropping Python 3.6). 

TODO
Determine: at what scipy version does the new namespace become available?
