### ISSUE TITLE
Add scqubits to conda-forge arm64 platform?

### ISSUE THREAD

**Issue by pacosynthesis** [scqubits/scqubits#125]
The `conda forge` channel has two platforms for osx: `osx-64` and `osx-arm64`, while scqubits is only available on the `osx-64` platform right now. Do we have plans for including scqubits for the `osx-arm64` platform as well? 

I tried installing scqubits with `pip` on my Apple M1 computer, with all the optional packages, and ran the test by `scqubits.testing.run()`; all the tests were passed.

Also would it be better to mention that the optional packages are required to pass all the pytests?

**Comment by jkochNU** [comment]
@pacosynthesis The following blog post may be a good starting point: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/. The fact that the conda-forge bot did not create an automatic PR makes me wonder whether there is actually still a problem we are missing. It is encouraging that qutip already has osx-arm64 versions (https://anaconda.org/conda-forge/qutip/files).

**Comment by jkochNU** [comment]
@pacosynthesis It appears that there's a long list of packages in queue to get osx-arm64 support: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt
I have added us to the queue: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2865
