### ISSUE TITLE
Adding coherence time calculations to scqubits GUI

### ISSUE THREAD

**Issue by petergthatsme** [scqubits/scqubits#132]
This issue is meant as a unitaryHACK bounty issue.
**Bounty**: $75

Some of the functionality of scqubits can be easily explored via it's jupyter-widgets-based GUI, which is discussed [here](https://scqubits.readthedocs.io/en/latest/guide/ipynb/gui.html).

We would like to extend this GUI functionality to include plots of the estimated coherence times. 

Coherence time calculations are already implemented for various qubits, as is explained in the [documentation](https://scqubits.readthedocs.io/en/latest/guide/guide-noise.html).

We envision for the updated GUI to, at the very least, for each qubit, show the [effective](https://scqubits.readthedocs.io/en/latest/guide/noise/ipynb/visualization.html#Effective-coherence-time-calculations) coherence time plotted versus the parameter that is being scanned-over.   

Using default coherence calculation parmaters would be a good start, although a more desirable outcome would allow users some flexibility. For example allowing users to select what noise channels should be included in the coherence time estimation, and/or allowing them to set some non-default options for each, would be welcome.

**Comment by jkochNU** [comment]
This has been incorporated with https://github.com/scqubits/scqubits/commit/605ad1ca8dc9e9f6fdd3289f1f8dd7d7e8389671, thanks to @sujoju.
