### ISSUE TITLE
[Other issue] Capacitive noise in fluxonium

### ISSUE THREAD

**Issue by AlesyaSokol** [scqubits/scqubits#162]
Hello,

I'm not sure if it's a bug or a lack of my understanding (if the latter - I'm open to hearing where I'm wrong), but I think there is a problem with a formula used for calculating capacitive noise for fluxonium qubit.

The [formula](https://scqubits.readthedocs.io/en/latest/guide/noise/depolarization.html#capacitive-noise) in the code is different from the one from the [paper cited as a reference to the code](https://journals.aps.org/prx/pdf/10.1103/PhysRevX.9.041041) (Eq. A5-A9). Also, I'd expect the noise operator in this case to be the flux operator (as in the reference), instead of the charge operator (as in the code), because for fluxonium, flux states are used. 

Could you please clarify why you use this equation to calculate the capacitive noise, instead of the one in the paper?

Thank you in advance,
Alesya

**Comment by petergthatsme** [comment]
Hi @AlesyaSokol 

Thanks for reaching out about this. 

One often maps flux to charge operators, and vice-versa (check out discussion in, for example, [here](https://arxiv.org/abs/2002.10653) on page 4), and so while the expressions for some of the decoherence channels may look dramatically different, they actually (should) lead to the same physics. 

I will close this for now, but if you find that we indeed have an error, even with this charge-flux replacement, please don't hesitate to comment on here, and we can update the code.
