### ISSUE TITLE
[Bug report] Confusing behavior with coupled fluxoniums

### ISSUE THREAD

**Issue by AlesyaSokol** [scqubits/scqubits#168]
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [x] I have checked the API documentation.
 - [x] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug

I want to make two capacitively coupled fluxoniums. There are two ways to do it:

1. Using built-in fluxonium objects + hilbertspace.add_interaction
The Hamiltonian will be the following (the capacitive energies of the fluxonium renormalize because the capacitance seen by fluxonium is now different):
$H = - E_{J1} \cos\phi_1 + \frac{1}{2} E_{L1} \phi_1^2 + 4(E_{C1} + \frac{E_{C1}^2}{E_{Cg}} n_1^2) - $ 
$- E_{J2} \cos\phi_2 + \frac{1}{2} E_{L2} \phi_2^2 + 4(E_{C2} + \frac{E_{C2}^2}{E_{Cg}} n_2^2) - $
$- \frac{8 E_{C1} E_{C2}}{E_{Cg}} n_1 n_2 $

2. Using Custom Circuits

The problem is, with these two methods I get different results, in particular, the anticrossing size is different.

For method (1), I get anticrossing_size_1 = 0.1338

And for (2) I get anticrossing_size_2 = 0.0946.

I've checked that the Hilbert space is large enough, so the further increase of the Hilbert space doesn't affect the result.

### Expected behavior

anticrossing_size_1 should be equal to anticrossing_size_2

### To Reproduce

Here is my code for (1):
```
import numpy as np
from qutip import *
import scipy as sp
import matplotlib.pyplot as plt
import matplotlib

import scqubits as scq
from scqubits import HilbertSpace, InteractionTerm

EC1 = 0.25
EC2 = 0.3
EJ1 = 1
EJ2 = 1
EL1 = 0.55
EL2 = 0.5
ECg = 1
flux1 = 0.495
flux2 = 0.45
cutoff = 20

fluxonium1 = scq.Fluxonium(
    EJ = EJ1, 
    EC = EC1+EC1**2/ECg, 
    EL = EL1,
    flux = flux1, 
    cutoff = cutoff,
    truncated_dim = cutoff
)

fluxonium2 = scq.Fluxonium(
    EJ = EJ2, 
    EC = EC2+EC2**2/ECg, 
    EL = EL2,
    flux = flux2, 
    cutoff = cutoff,
    truncated_dim = cutoff
)

hilbertspace = scq.HilbertSpace([fluxonium1, fluxonium2])

g = -8*EC1*EC2/ECg

hilbertspace.add_interaction(
    g_strength = g,
    op1 = (fluxonium1.n_operator(), fluxonium1),
    op2 = (fluxonium2.n_operator(), fluxonium2),
    id_str="fluxoniums",
    add_hc=False
)

H = hilbertspace.hamiltonian()

def update_hilbertspace(flux):
    fluxonium1.flux = flux

fluxes = np.linspace(0.43, 0.48, 21)

E01s = []
E02s = []

for flux in fluxes:
    update_hilbertspace(flux)
    evals = hilbertspace.eigenvals(evals_count=3)
    E01s.append(evals[1]-evals[0])
    E02s.append(evals[2]-evals[0])

anticrossing_size_1 = min(np.array(E02s) - np.array(E01s))
```

And for (2):

```
coupled_fl_yaml = """
        branches:
        - ["JJ", 1, 2, EJ1 = """+str(EJ1)+""", EC1 = """+str(EC1)+"""]
        - ["L", 1, 2, EL1 = """+str(EL1)+"""]
        - ["C", 2, 3, ECg = """+str(ECg)+"""]
        - ["JJ", 3, 1, EJ2 = """ +str(EJ2)+ """, EC2 = """+str(EC2)+"""]
        - ["L", 3, 1, EL2 = """+str(EL2)+"""]
        """
    
circuit = scq.Circuit.from_yaml(coupled_fl_yaml, from_file=False, ext_basis = 'discretized', 
                                truncated_dim = 250)
circuit.cutoff_ext_1 = 50
circuit.cutoff_ext_2 = 50

circuit.Φ1 = flux1
circuit.Φ2 = flux2

def update_flux(circuit, flux):
    circuit.Φ1 = flux

E01s = []
E02s = []

for flux in fluxes:
    update_flux(circuit, flux)
    evals = circuit.eigenvals(evals_count=3)
    E01s.append(evals[1]-evals[0])
    E02s.append(evals[2]-evals[0])

anticrossing_size_2 = min(np.array(E02s) - np.array(E01s))
```

### OS and version used (please complete the following information):
 - OS: Ubuntu
 - scqubits version 3.1.0
 - Python version 3.9.13

**Comment by saipavanc** [comment]
Hi @AlesyaSokol, thank you for raising the issue. I tried to work through the code you posted and found the following. First, I think the normalized capacitances you used to generate the eigenvalues using `Hilbertspace` are incorrect (which I will talk about in more detail in a following paragraph). 

Secondly, please note that the input to the Circuit module is a graph and it does not have any information as to the geometric placement of circuit elements in space. Therefore, the sign of the fluxes that the code generates is not always what the user expects. We suggest that the user first checks whether the flux signs are as they expect, if not flip the sign wherever necessary. In this case, it is necessary to flip the sign of `Φ2` in the Circuit module to make the results consistent. 

Coming back to the normalized capacitances, you can get the correct normalized capacitances by looking at the coefficients of $Q_1^2$, $Q_2^2$ and $Q_1Q_2$ from the symbolic Hamiltonian that the Circuit module generates. I found the coefficients using the following code snippet. You can easily verify that these coefficients are correct by starting with a Lagrangian and then making a Legendre transform to get to the Hamiltonian. 
```
coupled_fl_yaml = f"""
        branches:
        - ["JJ", 0, 1, EJ1 = {EJ1}, EC1 = {EC1}]
        - ["L", 0, 1, EL1 = {EL1}]
        - ["C", 1, 2, ECg = {ECg}]
        - ["JJ", 2, 0, EJ2 = {EJ2}, EC2 = {EC2}]
        - ["L", 2, 0, EL2 = {EL2}]
        """
    
circuit = scq.Circuit(coupled_fl_yaml, from_file=False, ext_basis = 'harmonic')
circuit.configure(transformation_matrix=np.identity(2))
circuit.cutoff_ext_1 = 30
circuit.cutoff_ext_2 = 30

circuit.Φ1 = flux1
circuit.Φ2 = -flux2

def update_flux(circuit, flux):
    circuit.Φ1 = flux

E01sc = []
E02sc = []

for flux in fluxes:
    update_flux(circuit, flux)
    evals = circuit.eigenvals(evals_count=3)
    E01sc.append(evals[1]-evals[0])
    E02sc.append(evals[2]-evals[0])

anticrossing_size_2 = min(np.array(E02sc) - np.array(E01sc))
```
```
# getting the normalized capacitance for fluxonium 2
circuit.hamiltonian_symbolic.coeff("Q2**2")/4
# result - EC1*EC2/(1.0*EC1 + 1.0*EC2 + 1.0*ECg) + EC2*ECg/(1.0*EC1 + 1.0*EC2 + 1.0*ECg)
```
```
# getting the normalized capacitance for fluxonium 1
circuit.hamiltonian_symbolic.coeff("Q1**2")/4
# result - 0.001953125*EC1*EC2/(0.001953125*EC1 + 0.001953125*EC2 + 0.001953125*ECg) + 0.001953125*EC1*ECg/(0.001953125*EC1 + 0.001953125*EC2 + 0.001953125*ECg)
```
```
# getting the coupling factor
circuit.hamiltonian_symbolic.coeff("Q1*Q2")
# result - 0.0078125*EC1*EC2/(0.001953125*EC1 + 0.001953125*EC2 + 0.001953125*ECg) + 4.0*EC1*EC2/(1.0*EC1 + 1.0*EC2 + 1.0*ECg)
```
The above code snippet is just the same as the code you posted, but with two differences. I changed the input file such that node 1 is set to ground node, and then set the transformation matrix to generate the new variables to an identity matrix. These two changes do not affect the numerical results, but help us to look at the symbolic Hamiltonian in the form we expect. In the last part of the code, I am extracting the coefficients for the renormalized capacitances which I will now use for the coupled fluxoniums using the Fluxonium module in scqubits. 

```
import numpy as np
from qutip import *
import scipy as sp
import matplotlib.pyplot as plt
import matplotlib

import scqubits as scq
from scqubits import HilbertSpace, InteractionTerm

EC1 = 0.25
EC2 = 0.3
EJ1 = 1
EJ2 = 1
EL1 = 0.55
EL2 = 0.5
ECg = 1
flux1 = 0.495
flux2 = 0.45
cutoff = 50
truncated_dim = 40

fluxonium1 = scq.Fluxonium(
    EJ = EJ1, 
#     EC = EC1+EC1**2/ECg,
    EC = 0.001953125*EC1*EC2/(0.001953125*EC1 + 0.001953125*EC2 + 0.001953125*ECg) + 0.001953125*EC1*ECg/(0.001953125*EC1 + 0.001953125*EC2 + 0.001953125*ECg),
    EL = EL1,
    flux = flux1, 
    cutoff = cutoff,
    truncated_dim = truncated_dim
)

fluxonium2 = scq.Fluxonium(
    EJ = EJ2, 
#     EC = EC2+EC2**2/ECg, 
    EC = EC1*EC2/(1.0*EC1 + 1.0*EC2 + 1.0*ECg) + EC2*ECg/(1.0*EC1 + 1.0*EC2 + 1.0*ECg),
    EL = EL2,
    flux = flux2, 
    cutoff = cutoff,
    truncated_dim = truncated_dim
)

hilbertspace = scq.HilbertSpace([fluxonium1, fluxonium2])

# g = -8*EC1*EC2/ECg
g = 0.0078125*EC1*EC2/(0.001953125*EC1 + 0.001953125*EC2 + 0.001953125*ECg) + 4.0*EC1*EC2/(1.0*EC1 + 1.0*EC2 + 1.0*ECg)

hilbertspace.add_interaction(
    g_strength = g,
    op1 = (fluxonium1.n_operator(), fluxonium1),
    op2 = (fluxonium2.n_operator(), fluxonium2),
    id_str="fluxoniums",
    add_hc=False
)

H = hilbertspace.hamiltonian()

def update_hilbertspace(flux):
    fluxonium1.flux = flux

fluxes = np.linspace(0.43, 0.48, 21)

E01s = []
E02s = []

for flux in fluxes:
    update_hilbertspace(flux)
    evals = hilbertspace.eigenvals(evals_count=3)
    E01s.append(evals[1]-evals[0])
    E02s.append(evals[2]-evals[0])

anticrossing_size_1 = min(np.array(E02s) - np.array(E01s))
```
The resultant variables `anticorssing_size_1` and `anticorssing_size_2` have the same value of 0.0863.

**Comment by jkochNU** [comment]
@saipavanc Thanks so much for looking into this in all the detail, very helpful!
I will give @AlesyaSokol a chance to comment before closing this issue.

**Comment by AlesyaSokol** [comment]
Hi @saipavanc, thank you for the detailed response!

I've tried your suggestions and noticed that flipping the sign of Φ2 changes the numerical result. I'm not sure I understand how this sign should be chosen. Also, shouldn't fluxonium spectrum be symmetrical with respect to zero, so the sign should not matter?

**Comment by saipavanc** [comment]
@AlesyaSokol, you are right that the spectrum of fluxonium should not depend on the sign of the external flux. But, when two fluxoniums are coupled, the relative direction of the external flux matters. That is what is making a difference in this particular case. Since, the circuit module does not have an idea as to the position of branches in space, the direction assigned to the external fluxes is not guaranteed to be consistent to the way we represent the circuit in a diagram (there are multiple ways to represent the same graph). 

As to the question about how the sign of the external flux should be chosen, I suppose the best way is to look at the symbolic Hamiltonian and see if the signs of external fluxes used in the expression are as expected. This is definitely feasible for small circuits, but for large circuits I do not have an answer as of now. Maybe comparing an external flux sweep with experimental data can help. @jkochNU Please feel free to add or edit my response to the question.

**Comment by AlesyaSokol** [comment]
@saipavanc ok, thank you for answering my questions, it looks like everything is correct.

By the way, the coefficients in the Hamiltonian that scq.Circuit gives can be simplified: 0.0078125/0.001953125 = 4, and then:
EC1' = EC1*(EC2+ECg)/(EC1+EC2+ECg),
EC2' = EC2*(EC1+ECg)/(EC1+EC2+ECg),
g = 8*EC1*EC2/(EC1+EC2+ECg)

**Comment by AlesyaSokol** [comment]
@saipavanc and about choosing flux sign - I checked, if I inverse the sign in the first approach that I use (coupled fluxoniums and hilbertspace) it gives consistent results with circuit approach. In experiment, I guess, the flux direction can also be reversed physically (if there are two separate flux lines). So there is no single correct flux direction, it just should be chosen consistently.

**Comment by saipavanc** [comment]
@AlesyaSokol I agree with your comments. And with regards to the coefficients, I did notice that they could be simplified, but I just wanted to ensure that I would use the same expression that the Sympy coeff function returned to avoid any confusion. 

I will go ahead and close the issue then.
