### ISSUE TITLE
[Suggestion/request] Coherence Times for Custom Circuits 

### ISSUE THREAD

**Issue by PhilippAumann** [scqubits/scqubits#169]
Hi,
I was wondering if it would be possible to make the noise estimation (coherence times) available for custom circuits?
If need be, I could also try to implement this and send a pull request.
Best,
Philipp

**Comment by PhilippAumann** [comment]
Thank you for your answer! I will try using the `spc-noise` branch for now - that looks quite promising!

Regarding the quasiparticle noise. Are there any arguments against using equation (136) of this paper: https://arxiv.org/pdf/1106.0829.pdf ?
Implementing this in the flux basis is quite straight-forward. For the charge basis this would call for implementing it in a single charge basis instead of the usual $2e$ charge basis.

**Comment by petergthatsme** [comment]
This has been implemented in V4.0 that was released recently.
