### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by benmcdonough20** [scqubits/scqubits#170]
### Documentation check
 - [x] I have checked the API documentation.
 - [x] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug
The bare eigenstate lookup function of HilbertSpace populates differently between the first and second time it is run.

### Expected behavior
Expected functionality of bare eigenstate lookup was to return an array of the bare eigenstate of a subsystem of the HilbertSpace object. This was done correctly, but array shape was slightly different depending on whether lookup dictionary was already populated.

### To Reproduce
Start with fresh kernel, then execute
```
import scqubits as sc

osc = sc.Oscillator(E_osc = 4)
hs = sc.HilbertSpace([osc])
hs.generate_lookup()
arr1 = hs.bare_eigenstates(osc)
print(arr1.shape)
arr2 = hs.bare_eigenstates(osc)
print(arr2.shape)
```
Output:
(6,6)
(1,6,6)

### OS and version used (please complete the following information):
 - OS: [e.g. Manjaro Linux, Windows 10, MacOS Ventura 13]
 - scqubits version: 3.1.0
 - Python version 3.10

### Additional Comments

I noticed in the definition of the bare eigenstates method that there was a reference to pre-slicing, but I don't believe this should be important in the context of HilbertSpace.

**Comment by jkochNU** [comment]
@benmcdonough20 Ben, thanks so much! If you are willing and able: check out branch `jk-ejecfit` which should (I hope) be addressing this issue.

**Comment by benmcdonough20** [comment]
@jkochNU Hello Prof. Koch,

I cloned the `jk-ejecfit` branch and I was able to reproduce the issue importing the local module, so maybe this is not related to the pre-slicing behavior.

I will spend some time trying to find the source of this behavior so that I can give more specifics!

**Comment by jkochNU** [comment]
![image](https://user-images.githubusercontent.com/19193849/206871616-e3e56e28-639a-4bd5-abac-df71e9674756.png)

@benmcdonough20 Are you sure you are importing the right branch (and have pulled all recent changes that I pushed yesterday)?

**Comment by benmcdonough20** [comment]
Absolutely! It is totally possible that I messed something up with the local import.

Here is the output of the code above:
```
 @utils.check_sync_status
    def bare_eigenstates(
        self,
        subsys: "QuantumSys",
        param_indices: Optional[Tuple[int, ...]] = None,
    ) -> NamedSlotsNdarray:
        """
        Return ndarray of bare eigenstates for given subsystems and parameter index.
        Eigenstates are expressed in the basis internal to the subsystems. Usually to be
        with pre-slicing.
        """
        param_indices_tuple = self.set_npindextuple(param_indices)
        subsys_index = self.hilbertspace.get_subsys_index(subsys)
        self._current_param_indices = slice(None, None, None)
        return self["bare_evecs"][subsys_index][param_indices_tuple]
```

**Comment by jkochNU** [comment]
@benmcdonough20 That indicates that you are not on the correct version and/or branch.
Output should be (note specifically the second but last line):
```
@utils.check_sync_status
    def bare_eigenstates(
        self,
        subsys: "QuantumSys",
        param_indices: Optional[Tuple[int, ...]] = None,
    ) -> NamedSlotsNdarray:
        """
        Return ndarray of bare eigenstates for given subsystems and parameter index.
        Eigenstates are expressed in the basis internal to the subsystems. Usually to be
        used with pre-slicing when part of `ParameterSweep`.
        """
        param_indices_tuple = self.set_npindextuple(param_indices)
        subsys_index = self.hilbertspace.get_subsys_index(subsys)
        self.reset_preslicing()
        return self["bare_evecs"][subsys_index][param_indices_tuple]
```

**Comment by benmcdonough20** [comment]
Ah, that is by bad! I did not know the correct command to clone a branch, and so I ended up just cloning the main branch of the repository.

I verified that I cloned the `jk-ejecfit` branch correctly, and the code ran as expected. Thanks for pointing this out!

Should I go ahead and close the issue?

**Comment by jkochNU** [comment]
@benmcdonough20 Glad this works now. I'll close, but don't hesitate to reopen (or post a new issue if something unrelated comes up). Thank you so much for taking the time to help making scqubits better. I'll merge this into the master branch momentarily.
