### ISSUE TITLE
[Bug report] hilbertspace.energy_by_bare_index

### ISSUE THREAD

**Issue by benmcdonough20** [scqubits/scqubits#172]
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [x] I have checked the API documentation.
 - [x] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug
The method `hilbertspace.energy_by_bare_index` raises an exception `AttributeError: 'numpy.ndarray' object has no attribute '_parameters'`

### Expected behavior
The behavior expected was for the output of `hilbertspace.energy_by_bare_index(bare_tuple)` to be the same as `hilbertspace.energy_by_dressed_index(hilbertspace.dressed_index(bare_tuple))`.

### To Reproduce
The error can be reproduced using the following code:
```
from scqubits import Oscillator, HilbertSpace, Transmon

tmon = Transmon(
    EJ=40.0,
    EC=0.2,
    ng=0.3,
    ncut=40,
)
osc = Oscillator(E_osc=5.7)
hs = HilbertSpace([osc,tmon])
hs.generate_lookup()

hs.energy_by_bare_index((0,0))
```

### OS and version used (please complete the following information):
 - OS: Manjaro Linux
 - scqubits version 3.1.0
 - Python version 3.10.6

### Additional context
This code was also tested on the `jk-ejectfit` branch and produced the same error.

**Comment by jkochNU** [comment]
I can confirm that bug & will produce a fix.

**Comment by jkochNU** [comment]
Bug fix issued under https://github.com/scqubits/scqubits/pull/174/commits/679039374e77e225c5de7309a8f9513c6d5b2ec2.

@benmcdonough20 Please confirm that the newest master version eliminates the issue.

**Comment by benmcdonough20** [comment]
I checked out the `jk-deprecations` branch and I can confirm that the issue is fixed!

The newest master branch still seems to produce the issue though. I checked the open pull requests and it seems like the changes haven't been merged into master yet, is this correct?

**Comment by jkochNU** [comment]
@benmcdonough20 Correct, still had to click on the "confirm merge" button. Done now!
