### ISSUE TITLE
Parameter dependent operators are not updated when doing matrix element sweep in `get_matelements_vs_paramvals`

### ISSUE THREAD

**Issue by Harrinive** [scqubits/scqubits#177]
### Bug description and expected behavior
In this code, I used two method to calculate a matrix element table, and I expect to obtain the same results (print True):
```
import scqubits as scq

qubit = scq.Fluxonium(
    EJ = 10,
    EC = 1,
    EL = 0.5,
    flux = 0.0,
    cutoff = 100,
    truncated_dim = 6,
)
table_1 = qubit.get_matelements_vs_paramvals("n_operator", "EL", [1]).matrixelem_table[0]

qubit.EL = 1
table_2 = qubit.matrixelement_table("n_operator")

np.allclose(table_1, table_2, rtol=1e-5)
```
With the current code, I got `False` here. 

### Further consequences
Then `qubit.plot_matelem_vs_paramvals()` gives a wrong result when sweeping n_operator over EL. Issue #114 is also an example of it. 

### My thought of the reason
For the fluxonium qubit, `qubit.n_operator()` depends on the value of `EL` as it is in calculation of the oscillator length `qubit.phi_osc()`. When doing a parameter sweep, we are calculating the matrix element with updated `evecs` and a unchanged operator. That's why we get a wrong answer.

### Other qubits and operators may also have this problem
For fluxonia, `phi_operator` and `n_operator` depends on `EL` and `EC` (in oscillator length). As issue #114 mentioned, `d_hamiltonian_d_flux` depends on `flux` in `TunableTransmon`. Those matrix elements are not calculated properly in the method `get_matelements_vs_paramvals` and there might be more examples.

**Comment by jkochNU** [comment]
Bug fix pushed to main with e8fccdf15706c5fee1a3ccbf3f21b5a886a81d57
![image](https://user-images.githubusercontent.com/19193849/223428726-d5b19b1d-c94a-4cd9-a041-5fce3b09cfb1.png)
