### ISSUE TITLE
Adding support for 1/f flux noise channel to the flux qubit class

### ISSUE THREAD

**Issue by petergthatsme** [scqubits/scqubits#185]
scqubits can estimate coherence times of various quantum systems. However, not all types of "noise channels" have yet been implemented in all the qubits classes.  

The goal of this enchancement is to add support for calculating the coherence times (and rates) due to [1/f flux noise](https://scqubits.readthedocs.io/en/latest/guide/noise/dephasing.html#f-noise) in the `FluxQubit` class. 

The core functionality of estimating 1/f noise coherence times is already implemented in the [tphi_1_over_f](https://scqubits.readthedocs.io/en/latest/api-doc/_autosummary/scqubits.core.noise.NoisySystem.html#scqubits.core.noise.NoisySystem.tphi_1_over_f) method of `NosySystem`, which `FluxQubit` inherits from. That method requires that the qubit class implements a way to calculate an operator representing a flux derviative of the Hamiltonian - something that needs to be implemented. 

Possible Implementation steps: 

- Implement a new method called `d_hamiltonian_d_flux()` in the `FluxQubit` class. This method should calculate an operator representation of the derivative of the Hamiltonian with respect to flux (see other qubit classes for examples). 

- Add `t_phi_1_over_f_flux` to `FluxQuibt.supported_noise_channels` class-method. This will make `tphi_1_over_f` as an officially supported noise channel for the flux qubit. 

- Update [scqubits/tests/test_noise.py](https://github.com/scqubits/scqubits/blob/main/scqubits/tests/test_fluxqubit.py) so that it includes the `tphi_1_over_f_flux` calculation (`data['FluxQubit']` will need a new entry).

**Comment by manulpatel** [comment]
Hello @petergthatsme! I am new to scqubits and would like to work on this issue as a part of Unitary Hack. Could you please assign me?

**Comment by D3vanagar1** [comment]
Hi, I would also like to work on this issue as part of the Unitary Hack. Is it possible for me to be assigned to this challenge? 
Thanks.

**Comment by petergthatsme** [comment]
thanks for your interest @hrahman12 
I think at this stage @D3vanagar1 has already submitted a pull request - i just need a moment to review/approve it (hopefully in a day or two).

**Comment by petergthatsme** [comment]
hey @golanor  just making sure you saw the comment on your pull request - you have two copies of d_hamiltonian_d_flux() (presumably some copy/paste typo?)... once you update that, we'll be able to close and finalize this bounty. Thanks.

**Comment by petergthatsme** [comment]
@golanor can you post a message in this thread? for some reason, at the momemnt, github is not letting me assign you to this issue (which is a requirement for you to collect the bounty, once we close it). Thx.

**Comment by petergthatsme** [comment]
Closing. Thanks again for participating.
