### ISSUE TITLE
[Bug report] creation and annihilation operators for custom circuits

### ISSUE THREAD

**Issue by tibidabo** [scqubits/scqubits#191]
Dear scQubits Team,

How can I implement a creation and annihilation operator for custom circuits?

I would like to use the composite Hilbert Space feature with my own qubit design implemented in the custom circuits feature. I intend to build semiclassical models of multiple custom qubits and interact with them using QuTiP.

I already posted an [[issue related to the same project](https://github.com/scqubits/scqubits/issues/190)](https://github.com/scqubits/scqubits/issues/190), which was successfully resolved :-).

Is it correct that this feature is not implemented?
Is there a workaround?
Do you plan to implement such compatibility?

Thank you very much,

Chris

# Minimal working example

### Documentation check

If the bug manifests in unexpected behaviour (as opposed to a crash), confirm that you have consulted the
[[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

-  I have checked the API documentation.
-  I could not locate relevant information in the documentation or information is missing.

I checked the read-the-docs and the examples without finding a helpful reference for the problem. Looking deep into the code did not reveal how to solve the issue eighter. 

## Minimal working example

- using the code from the [[scQubits examples](https://github.com/scqubits/scqubits-examples/blob/441a6a1ac7e48ef05a67e7fe9e5d00f8a1378dc5/examples/demo_hilbertspace.ipynb)](https://github.com/scqubits/scqubits-examples/blob/441a6a1ac7e48ef05a67e7fe9e5d00f8a1378dc5/examples/demo_hilbertspace.ipynb)

```
import scqubits as scq

# ref for parameters: Table I in Weber, Steven J., Gabriel O. Samach, David Hover, Simon Gustavsson, David K. Kim, Alexander Melville, Danna Rosenberg, et al. “Coherent Coupled Qubits for Quantum Annealing.” ArXiv:1701.06544 [Cond-Mat, Physics:Quant-Ph], June 6, 2017. https://doi.org/10.1103/PhysRevApplied.8.014004.

# define qubit parameters
csfq4jj_yaml = """# CSFQ4JJ
branches:
- ["JJ", 1, 2, 102.31680319713882, 9.68511466232956]
- ["JJ", 2, 3, 102.31680319713882,  9.68511466232956]
- ["JJ", 3, 4, 102.31680319713882,  9.68511466232956]
- ["C", 1, 4, 0.36547602499356835]
- ["JJ", 1, 4, 38.741313831926355,  25.578636159485757]
"""

# CSFQ4JJ1
csfq4jj1 = scq.Circuit(csfq4jj_yaml, from_file=False, ext_basis="discretized")
csfq4jj1.truncated_dim = 4
csfq4jj1.Φ1 = 0.5

# CSFQ4JJ2
csfq4jj2 = scq.Circuit(csfq4jj_yaml, from_file=False, ext_basis="discretized")
csfq4jj2.truncated_dim = 4
csfq4jj2.Φ1 = 0.5

# define composite hilbertspace of two custom flux qubits
hilbertspace = scq.HilbertSpace([csfq4jj1, csfq4jj2])

if True:
    # Option A: operator product specification via callables
    g = 0.1

    hilbertspace.add_interaction(
        g_strength=g,
        op1=csfq4jj1.creation_operator,
        op2=csfq4jj2.annihilation_operator,
        add_hc=True
    )
else:
    # Option B: string-based specification of interaction term
    g = 0.1
    hilbertspace.add_interaction(
        expr="g * a.dag() * a.dag() * b",
        op1=("a", csfq4jj1.annihilation_operator),
        op2=("b", csfq4jj2.annihilation_operator),
        add_hc=True
    )

print(hilbertspace)

dressed_hamiltonian = hilbertspace.hamiltonian()
dressed_hamiltonian

evals, evecs = dressed_hamiltonian.eigenstates(eigvals=4)
print(evals)
```

### Describe the bug

For both options of creating the operators, I get the following error messages:

```
(flux-qubit-theory) two-flux-qubit-simulator-playground % python 230607_CustomCircuit_defineoperators_example.py
Traceback (most recent call last):
  File "two-flux-qubit-simulator-playground/230607_CustomCircuit_defineoperators_example.py", line 42, in <module>
    op1=csfq4jj1.creation_operator,
AttributeError: 'Circuit' object has no attribute 'creation_operator'
```

### Expected behaviour

I would like to implement a coupling between the two qubits in the composite Hilbertspace and drive the system later with QuTiP. Therefore I need the creation and annihilation operators in the custom circuit class. 

### OS and version used:

- OS: macOS 13 (Apple M1)
- scqubits version 3.1.0
- Python version 3.11.0

**Comment by saipavanc** [comment]
Hi Chris,

The operator names are not the same for `Circuit` objects like the other qubit objects in `scqubits`. To see the list of operators available for a circuit object. You can look at `csfq4jj1.operators_by_name.keys()` to give you a list of operator names that are available. 
```
dict_keys(['sinθ1_operator', 'sinθ2_operator', 'sinθ3_operator', 'cosθ1_operator', 'cosθ2_operator', 'cosθ3_operator', 'n1_operator', 'n2_operator', 'n3_operator', 'I_operator'])
```
And each of that operator can be called like a method to the Circuit object. For example:
```
csfq4jj1.n2_operator().
```
Do note that these correspond to the symbols which are used in the Hamiltonian expression printed out by the method `sym_hamiltonian()`.

**Comment by tibidabo** [comment]
Thank you very much! You are absolutely right. It was a conceptual error on my side and not a problem with scQubits. Thank you for your constructive advice. I am sorry for cluttering your issues with conceptual questions, and please point me to a better place if there is any.
