### ISSUE TITLE
[Other issue] typo in the comment

### ISSUE THREAD

**Issue by XiaotongNi** [scqubits/scqubits#197]
In https://scqubits.readthedocs.io/en/v3.2/guide/hilbertspace/ipynb/hilbertspace.html
```
tmon1 = scq.Transmon(
    EJ=40.0,
    EC=0.2,
    ng=0.3,
    ncut=40,
    truncated_dim=4     # after diagonalization, we will keep 3 levels
)
```

The comment of the last line seems wrong?

**Comment by jkochNU** [comment]
Thank you, indeed - will fix!

**Comment by jkochNU** [comment]
Fixed with commit https://github.com/scqubits/scqubits-doc/commit/20ad62ed899b179c97fa47ebf0113e137eaf4aef
