### ISSUE TITLE
[Suggestion/request] Schrieffer–Wolff Transformation

### ISSUE THREAD

**Issue by tibidabo** [scqubits/scqubits#201]
Do you plan to implement Schrieffer–Wolff Transformation? I refer to methods in [1] to study the superconducting circuits as effective Hamiltonians. I use it often to connect superconducting circuits to algorithms formulated on a computational basis in terms of Pauli matrices. 

If you think the SWT matches your strategy of scQubits, I would consider contributing it to the code.

[1] Consani, Gioele, and Paul A. Warburton. “Effective Hamiltonians for Interacting Superconducting Qubits: Local Basis Reduction and the Schrieffer–Wolff Transformation.” New Journal of Physics 22, no. 5 (May 2020): 053040. https://doi.org/10.1088/1367-2630/ab83d1.

**Comment by petergthatsme** [comment]
Thanks for reaching out and your suggestion @tibidabo.
At this very  moment we have no plans to implement SW transformations within scqubits. At first glace I would think this is maybe a job for some other, separate package? 

I will close this for now, but if something changes on our side, we will keep this in in mind.

**Comment by iarayad** [comment]
Hi all!
My colleagues and I have recently implemented a Python package to do perturbation theory numerically and symbolically.
The documentation is [here](https://pymablock.readthedocs.io/), with a few tutorials and explanation of the algorithm.
Would this be useful for what you had in mind? I'm curious!

**Comment by iarayad** [comment]
Hey all, have you had a chance to look at this? @petergthatsme 
Our paper is out on [arxiv today](https://arxiv.org/pdf/2404.03728.pdf) and I'd be happy to discuss if the implicit method can help to speed up calculations in scqubits.

**Comment by ZhaoTianPu** [comment]
As an addition to @petergthatsme's comment, although implementing numerical SWT is probably out of scQubits's scope, we found your work very interesting, specifically @Harrinive (Danyang Chen) was earlier trying to develop methods to perform numerical SW for some composite systems, and have tried your package.
