### ISSUE TITLE
2pi factor in the definition of the interaction strength g

### ISSUE THREAD

**Issue by AdRs21** [scqubits/scqubits#204]
Hello,
The default units of scqubits are in Hz (frequencies). However, when doing a Composite Hilbert Space, it seems to me that the unit of the interaction strength is considered to be in rad/s (angular frequencies). Indeed, this is is consistent with the equation written [here](https://scqubits.readthedocs.io/en/v3.3/guide/hilbertspace/ipynb/hilbertspace.html) and with the gap of an avoided crossing, or the frequency of Vacuum Rabi oscillations.
For me, this is very confusing. I think all the parameters we give to scqubits should be all frequencies.

**Comment by petergthatsme** [comment]
Thanks for the question @AdRs21.

When building HilbertSpace objects, the units of interactions as well as bare components are actually assumed to be the same: GHz, by default - i.e., we don't multiply the interaction-only by 2\pi. Is there an example that you've come across that shows that's not the case? (As a side note, the scqubits assumptions about units are most important/relevant when labeling plots, and during coherence calculations.)

It is definitely true, however, that we may use \omega when defining various Hamiltonians in the docs (especially when discussing oscillators), which as you point out, may be confusing. We could (1) update docs and not use \Omega, but \nu or something... or (2) add a note in relevant places, highlighting what the code does.

I will think about what makes more sense, and sort this out for the next release. 

In the mean time closing this, but please reply/reopen if something is still off.

**Comment by AdRs21** [comment]
Hello, thanks for the reply.
This is what I thought at first, but I tested an avoided crossing and vacuum Rabi oscillations, and I have the impression that I need a 2pi factor in the definition of g to be consistent.
Here is my code:
```python
import qutip as qt
import scqubits
import numpy as np
import matplotlib.pyplot as plt

def freq_fluxo(params, N_fluxonium = 7):
    fluxonium = scqubits.Fluxonium(EJ = params[0],
                                    EC = params[1],
                                    EL = params[2],
                                    flux = 1/2,
                                    cutoff = 110,
                                    truncated_dim=N_fluxonium)
    evals = fluxonium.eigenvals()
    return evals[1]-evals[0]

def create_system(params, g =0.111, N_fluxonium = 7, N_resonator = 30):
    fluxonium = scqubits.Fluxonium(EJ = params[0],
                                    EC = params[1],
                                    EL = params[2],
                                    flux = 1/2,
                                    cutoff = 110,
                                    truncated_dim=N_fluxonium)
    resonator = scqubits.Oscillator(
            E_osc=params[3],
            l_osc = params[4],
            truncated_dim=N_resonator)
    full_system = scqubits.HilbertSpace([fluxonium, resonator])

    full_system.add_interaction(g_strength = g,op1 = fluxonium.n_operator,op2 = resonator.creation_operator,add_hc = True)
    return fluxonium, resonator, full_system

def transition_frequency(system, i, j):
    return system.energy_by_dressed_index(i) - system.energy_by_dressed_index(j)

# fluxonium parameters (GHz)
EJ = 4.
EC = 1.
EL = 1.

g = 0.111 # what is the unit ?

E10Bare = freq_fluxo([EJ,EC,EL])
L_osc = 1.


# avoided crossing
E10L = []
EcavL = []
Delta = np.linspace(-5e-2,5e-2,41) #detuning GHz
EcavBareL = Delta+E10Bare
for Ecav in EcavBareL :
    params = [EJ, EC, EL, Ecav,  L_osc]
    fl, res, full_sys = create_system(params, g = g, N_fluxonium = 7, N_resonator = 50)
    
    full_sys.generate_lookup()
    E10L.append(transition_frequency(full_sys,full_sys.dressed_index((0,0)), full_sys.dressed_index((1,0))))
    EcavL.append(transition_frequency(full_sys,full_sys.dressed_index((0,0)), full_sys.dressed_index((0,1))))
    
E10L = np.array(E10L)
EcavL = np.array(EcavL)


Ep, Em = np.maximum(EcavL,E10L), np.minimum(EcavL,E10L)
fig, axs = plt.subplots()
axs.plot(Delta, np.abs(Ep-Em),label=r"$E_+-E_-$")
axs.set_xlabel(r"$\Delta$ (GHz)")
axs.set_ylabel(r"$E_+-E_-$ (GHz)")

print("gap",np.min(Ep-Em))
print("2g",2*g)
print("2g/(2pi)",2*g/(2*np.pi))

# resonant vacuum rabi oscillations
Ecav = E10Bare
params = [EJ, EC, EL, Ecav,  L_osc]
fl, res, full_sys = create_system(params, g = g, N_fluxonium = 7, N_resonator = 50)
_, _, full_sys_bare = create_system(params, g = 0, N_fluxonium = 7, N_resonator = 50)

H = full_sys.hamiltonian()
evals, ekets = H.eigenstates()
full_sys.generate_lookup()

H_bare = full_sys_bare.hamiltonian()
evals_bare, ekets_bare = H_bare.eigenstates()
full_sys_bare.generate_lookup()

tlist = np.linspace(0,100,101)
psi0 = ekets_bare[full_sys_bare.dressed_index((0,1))]
psi1 = ekets_bare[full_sys_bare.dressed_index((1,0))]

result = qt.sesolve(2*np.pi*H, psi0, tlist, [psi0.proj(),psi1.proj()])

fig, axs = plt.subplots()
axs.plot(tlist,result.expect[0])
axs.plot(tlist,result.expect[1])
axs.set_xlabel('t (ns)')
axs.set_ylabel('population')

print('2pi/(2g)',2*np.pi/(2*g))
```
It returns
```
gap 0.03442508755488349
2g 0.222
2g/(2pi) 0.035332397366400765
2pi/(2g) 28.302636518826965
```
and produces the following figures:
![Figure 3](https://github.com/scqubits/scqubits/assets/54591165/73133e5f-a896-41a6-8bbc-ee33d60291b9)
![Figure 4](https://github.com/scqubits/scqubits/assets/54591165/e7c32976-b63c-4101-a1c6-320a66045971)


That is, to me the gap of the avoided crossing is given by 2g only if I divide g by 2pi, whereas everything else is in GHz. Also the period of the Vacuum Rabi Oscillation should be 2pi/(2g) when g is in (2pi)GHz (see for example [Lleddo et al., Nature (2023)], which seems consistent with the second figure.

Am I doing something wrong?

**Comment by petergthatsme** [comment]
thanks for sending the code - i will take a look at it when i have a moment. Reopening this for now, to help keep track of it.

**Comment by petergthatsme** [comment]
I had a quick glance at your code. It looks like you're looking at a fluxonium-resonator system, hence the energy splitting gets renormalized by the charge matrix element (which in general will not be 1 as it is for a transmon, say). Maybe that's the confusion here? 

If in your code you vary the fluxonium parameters, you should see the splitting change, because the matrix element will change (i haven't ran your code, but this would be trivial for you to try, i.e. play with EJ/EC/EL of the qubit). 

Let me know if I'm missing something.

**Comment by AdRs21** [comment]
Oh, many thanks, I was not aware that the matrix element will renormalised the splitting, and I was in the unlucky situation where this element was very close to 1/(2pi).
Then I guess it make sense for me, ie all the variables in scqubits are in coherent units (let's say typically GHz). I will thus close this issue.
Thanks :)
