### ISSUE TITLE
[Other issue] Loading the GUI

### ISSUE THREAD

**Issue by GWG-16** [scqubits/scqubits#205]
I'm having some trouble loading the GUI, keeps giving me error messages.

**Comment by petergthatsme** [comment]
Could you show us what error messages you're getting? Are you running the latest version of scqubits? Also, how did you install scqubits, through conda, pip or from source? 
One thing to try, would be to reinstall scqubits (and the dependencies) to see if that fixes things.

**Comment by GWG-16** [comment]
﻿Thank you for getting back to me. I figured it out, I was running a version of python that scqubits didn’t support. Have a good one!On Jan 29, 2024, at 08:19, petergthatsme ***@***.***> wrote:﻿
Could you show us what error messages you're getting? Are you running the latest version of scqubits? Also, how did you install scqubits, through conda, pip or from source?
One thing to try, would be to reinstall scqubits (and the dependencies) to see if that fixes things.

**Comment by petergthatsme** [comment]
great, closing this now.
