### ISSUE TITLE
[Bug report] Long runtime to update parameters

### ISSUE THREAD

**Issue by antoniolrm** [scqubits/scqubits#207]
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [x] I have checked the API documentation.
 - [x] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug

I realized that updating system parameters takes as long or even longer than recreating the original circuit with a new set of parameters. I tried updating the parameters both as `circuit.param = new_value` (which seems to be [recommended for parameter sweeps](https://scqubits.readthedocs.io/en/latest/guide/parametersweep/ipynb/paramsweep2.html#Creating-a-ParameterSweep-object)) as well as `cicruit.set_params(**{'param':new_value}`.

Stopping the parameter update before it was over showed me that `scqubits` was running `sympy` routines. It made me realize that it was reconstructing the system from scratch. Even though there was no need for it since the symbolic Hamiltonian would not depend on the numerical values of the parameters.

Moreover, if I update a set of parameters, [this `for` loop](https://github.com/scqubits/scqubits/blob/2f3ba5f80defdbb206d9bb189c0279be1884311d/scqubits/core/qubit_base.py#L254) seems to run that long step once per parameter. So in the end it takes longer updating two parameters than creating a new system with new default parameter values.

### Expected behavior

I'd expect that updating numerical parameters would take almost no time. However, It takes longer than creating the system itself. Thus parameter sweeps seem to take much longer than necessary.

### To Reproduce

Creating the zero-pi qubit from the examples takes about 60ms:
```python
zp_yaml = """# zero-pi
branches:
- ["JJ", 1,2, EJ = 10, 20]
- ["JJ", 3,4, EJ, 20]
- ["L", 2,3, 0.008]
- ["L", 4,1, 0.008]
- ["C", 1,3, 0.02]
- ["C", 2,4, 0.02]
"""
zero_pi = scq.Circuit(zp_yaml, from_file=False)
```
whereas running `zero_pi.EJ = 1` takes about 100ms. With larger systems the problem remains, making the update of a couple of parameters take minutes.

### OS and version used (please complete the following information):
 - OS: macOS
 - scqubits version 3.3.0
 - Python version 3.11

### Additional context

Perhaps that is not the recommended way to update parameters and I am missing something else. So if there is another way to perform this task with smaller runtime it would be very helpful.

**Comment by saipavanc** [comment]
Thank you for filing this issue. For the particular Circuit code you shared, I got the following results:
![image](https://github.com/scqubits/scqubits/assets/79005467/63cd5de0-2dd6-4554-9957-8a1137223647)

This seems different from what you are observing. Could you please check if this is what you get as well? I observe something similar with a symbolic capacitance parameter as well.

It is possible that the package which is in the main branch, or the conda repo, is inefficient. I have made significant changes recently with regards to parameter updates and we are going to push another major release in the next few days. Hopefully that will address some of the issues. We have also tried using the Circuit module for larger circuits and have not noticed such significant slowdowns, though I will try to see if I can run some more tests to verify the same.

**Comment by antoniolrm** [comment]
@saipavanc it's indeed better. I checked with `timeit` and got similar results to yours. However, the problem remains IMO. Note that changing two parameters already takes as long as creating the circuit. I tried it also with a larger circuit and got something similar: updating the parameter takes half of the time of the full construction. I'm mostly surprised by the fact that currently, this parameter update seems to run steps that won't change the outcome: *e.g.* recomputing the symbolic Hamiltonian is unnecessary.

Is the upcoming release avoiding this route to substitute parameters?

**Comment by antoniolrm** [comment]
To give an actual example, this is what I got for a specific larger circuit that I'm working on. It takes about 10s to change a single numerical parameter. So a 2-parameter grid scan with 100 points along each axis takes ~2e5 seconds (more than 2 days), and I want to run many of those. I'd expect that the bottleneck for the numerics would be the dense diagonalization which takes only ~25ms per point (so ~5min for the full scan).

<img width="709" alt="Screenshot 2024-02-26 at 19 10 34" src="https://github.com/scqubits/scqubits/assets/49452874/b3c5a84e-e76a-48f1-9a09-5d16cbf2c9eb">

**Comment by saipavanc** [comment]
I understand, with big circuits, specifically with capacitive symbolic parameters the process is slow as it needs to go back to the SymbolicCircuit instance to avoid the inversion of symbolic capacitance which is even slower. Can you give the branch `spc-higher-order-branches` a try with your larger circuit and see if you are getting similar or bettter results? That would be very useful, as I can make the necessary changes or suggest something to make it more efficient.

**Comment by antoniolrm** [comment]
It took me a while, but as I see the branch was already merged. I checked the new version and it looks indeed much faster. Thank you!

**Comment by saipavanc** [comment]
Thank you for letting us know! I will close the issue now.
