### ISSUE TITLE
[Suggestion/request] Allow Henries as physical unit for Josephson junction branch parameter in custom circuits

### ISSUE THREAD

**Issue by zachparrott** [scqubits/scqubits#213]
I greatly appreciate the recent added feature for custom circuits to be able to use more physical units relevant to experimentalists than just in GHz. This saves some lines of code where I had to convert it all myself beforehand. I would like to suggest being able to specify a Josephson junction by its linear inductance in Henries not just in Amperes for its critical current (or energy units). This is how I often go about design circuits, especially with weakly anharmonic circuits when I might be starting with a linear analogous LC system.

**Comment by saipavanc** [comment]
I recently pushed a commit to the branch `spc-higher-order-branches`. Please feel free to use that branch for the calculations, and let us know if you come across any other issues. 

This commit will be incorporated in the main branch in one of the future sub-releases.
