### ISSUE TITLE
In the custom circuit class, no method to return the wavefunction

### ISSUE THREAD

**Issue by pdparakh108** [scqubits/scqubits#217]
In the circuit class, there is a method to plot the wavefunction [Circuit.plot_wavefunction], but no method that returns the wavefunction itself. It would be very useful to be able to get the wavefunction data as a numpy array to be able to manipulate it on our own.

**Comment by pdparakh108** [comment]
Ideally this method would allow the user to also specify the basis in which the wavefunction is returned (it is currently plotted in the phi basis, so choosing either this or the default basis would be helpful).

**Comment by saipavanc** [comment]
Hi @pdparakh108, the wavefunctions of the Circuit instance can be accessed in the same way as for any other qubit instance - which is `Circuit.eigensys()`, which returns a tuple of eigenenergies and the corresponding wavefunctions in the basis that is defined for the Circuit instance (If hierarchical diagonalization is used, the wavefunction will be in the product basis of the subsystems it comprises). If you would like to get the data for the wavefunctions that are being plotted, you can use the following method as well:

```python
plot_data = circ.generate_wf_plot_data(
            which=1,
            var_indices=(1,2),
            eigensys=esys,
            change_discrete_charge_to_phi=True,
            grids_dict=circ.discretized_grids_dict_for_vars(),
        )
```

Where I am using a method which is not described in the documentation. But, this is the very method that is used internally to generate the date for plotting the wavefunction. Please let us know if that helps.

**Comment by pdparakh108** [comment]
Hi, 

Thank you so much! This is very helpful. 

Best, 
Pranav
