### ISSUE TITLE
Short tutorial video on using scqubits

### ISSUE THREAD

**Issue by petergthatsme** [scqubits/scqubits#218]
We ask that you make a short (4-6 minutes) tutorial video about some aspects of using scqubits. This video could include going through and explaining one of the tutorial notebooks that has already been written (see [here](https://github.com/scqubits/scqubits-examples/tree/master/examples) for examples), or alternatively creating a custom notebook and explaining what it does. The latter option is prefered.

Some examples of what such a video would look like are shown [here](https://www.youtube.com/watch?v=cRNOm5AM6zc) or [here](https://www.youtube.com/watch?v=baBQy1IUOJE).

Our **most desired topic** would be related to using the `Circuit` module (discussed in the docs [here](https://scqubits.readthedocs.io/en/v4.0/guide/circuit/ipynb/custom_circuit_root.html) and in various subsections). Ideally, the video should include some discussion on how to use the latest addition related to estimating coherence times in custom circuits (see [here](https://scqubits.readthedocs.io/en/v4.0/guide/circuit/ipynb/custom_circuit_coherence_estimates.html)). A useful starting point could be this [notebook example](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_customcircuit.ipynb).

Optionally, other topics would be also fine to consider. Potential interesting starting notebooks could be:
[demo_qutip_fluxoniumreset.ipyn](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_qutip_fluxoniumreset.ipynb)
[demo_qutip_fluxoniumcz.ipynb](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_qutip_fluxoniumcz.ipynb)
[scqubits_paper_source_code.ipynb](https://github.com/scqubits/scqubits-examples/blob/master/examples/scqubits_paper_source_code.ipynb)

Alternatively putting together a completely "custom" notebook from scratch that includes some new discussion that we don't yet cover, or even some combination of what's already been done, or maybe one that reproduces results from a publication, would also be great. An example might be a notebook that explores performing a gate operation on a noisy transmon qubit (such a notebook would include parts of content presented in [here](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_transmon.ipynb) and [here](https://github.com/scqubits/scqubits-examples/blob/master/examples/demo_noise.ipynb)).

Specific requirements:  

- Choose a scqubits tutorial notebook from [here](https://github.com/scqubits/scqubits-examples/tree/master/examples) or alternatively write your own - it could be some combination of content from ones that already exist. 

- Reply with a comment to this bounty that includes a few sentences (could be in point-form, i.e., a sentence per section in the notebook you want discuss) that outlines what your tutorial would cover and what which aspects of the code and relevant physics you aim to highlight.

- Put together a 4-6 minute video

- Either upload the video to youtube and provide a link to it. Alternatively provide a link to where the video could be downloaded from (e.g. dropbox). In the latter case, please explicitly write that you agree that we upload your video to the the @scqubits youtube channel.

**Comment by jyotiraj-code** [comment]
Hi @petergthatsme I would like to make a tutorial video on the "Coherence Estimates of 0-Π-qubit" based on the paper Peter Groszkowski et al 2018 New J. Phys. 20 043053. Do the video need to be unlisted or can I directly publish it?

**Comment by petergthatsme** [comment]
Thanks @jyotiraj-code. 
You can directly publish it to your youtube account (or somewhere similar). 
Please note that currently some work will be needed to reproduce all the results from that paper; all the relevant noise channels for ZeroPi (and FullZeroPi) have not been implemented (yet?) in scqubits. However, this is a great idea... and even if you can reproduce some of the results from that (or other papers) and describe those in a video that would be fantastic from our side.

**Comment by jyotiraj-code** [comment]
Thank you @petergthatsme for the recommendations, I have almost finished creating the jupyter notebook and soon shoot the video. Definitely, some coupling mode (such as zeta-mode) and noise methods( critical current noise) for the zero-pi qubit has yet to be created. I am taking into consideration only the available documentation to create the tutorial and showcase some similar results related to the paper mentioned. 

Moreover, I had a doubt in the depolarization channel as it doesn't mention the use of t1_inductive methods but the same methods are mentioned as valid in the zero qubit of the qubit section of the documentation. As mentioned in the Smith et al (2020) and Nguyen et al (2019) it seems valid to consider the t1_inductive method but were missing from the Peter Groszkowski et al 2018 as a probable cause of the depolarization noise (or maybe I am missing out?). Whatsoever, it seems there need to be some documentation changes to the depolarization section to be done in the documentation.

**Comment by jyotiraj-code** [comment]
Hi @petergthatsme I have published the tutorial video. You can access it through this link (https://www.youtube.com/watch?v=4jLCypzJB84&t=1521s). The corresponding custom jupyter notebook can be accessed through this link (https://colab.research.google.com/drive/1OS0QekDzEYMBrSFXKETysRlhT27RxSqh?usp=sharing). 

In the tutorial I have included:
- Custom Circuit of zero-pi qubit
-  Its H and L calculations
- Different Noise and Coherence Estimates
- And finally the visualization plots of different parameters

The video runtime is long due to the inclusion of theory as well as the code explanations part. I hope it won't be a hardship for short attention spanners :)

Please let me know the remarks regarding the upload and if it is good enough to close the issue.

**Comment by petergthatsme** [comment]
Thanks for putting in the effort and making the video - I assigned the bounty to you now. 

Regarding the inductive loss; i can't remember why we didn't include it in the 2018 paper, but i think the subtelty was that the inductance for some of the more extreme ("deep zero pi regime") parameters was/is not achievable experimentally, hece it was not clear that the "stanard calculation" would be valid in that limit.

**Comment by jyotiraj-code** [comment]
Thanks @petergthatsme for the review. It's good to know that there is a scope to improve the experimental results. I would like to tell you that I have been working on a project related to the study of decoherence in transmon qubits in a summer project this year and thanks to UnitaryHack that I got introduced to this python package which would be valuable for simulations. Whatsoever, I am definitely interested to contribute more to the community in the meantime.
