### ISSUE TITLE
Enhancement of the `plot_transitions()` method

### ISSUE THREAD

**Issue by petergthatsme** [scqubits/scqubits#219]
`plot_transitions()` is a method of class `ParameterSweepBase` which can be used for plotting energies associated with various transitions as a function of a scanned parameter. An example of how it can be used is presented [here](https://scqubits.readthedocs.io/en/v4.0/guide/parametersweep/ipynb/paramsweep2-transitions.html#Transition-plots).
 
We are looking to add an enhancement where one can pass lists of tuples as arguments `initial` and/or `final`, with **specific** state labels that represent initial and final transition end-points of transitions that should be plotted. So for example calling:

        sweep.plot_transitions(initial=[(1,2,4), (1,3,1)], final=[(0,1,0)])

should lead to (only) transitions between levels with labels (1,2,4)<->(0,1,0) and (1,3,1)<->(0,1,0) being plotted. 

These changes should not break current code, and should be documented in the method's docstring.

(It would of course be great, if this addition would be also briefly explained in the [documentation](https://github.com/scqubits/scqubits-doc) - but that is not part of the bounty).

**Comment by anushkrishnav** [comment]
I will work on this

**Comment by petergthatsme** [comment]
Great. No need to assign. Please feel free to work on this. Yes the old format from passing in final state  should also work.

**Comment by anushkrishnav** [comment]
Currently working on this will send a PR shortly

**Comment by petergthatsme** [comment]
let us know if you are having any issues @anushkrishnav  and if we can help in any way.

**Comment by anushkrishnav** [comment]
> `plot_transitions()` is a method of class `ParameterSweepBase` which can be used for plotting energies associated with various transitions as a function of a scanned parameter. An example of how it can be used is presented [here](https://scqubits.readthedocs.io/en/v4.0/guide/parametersweep/ipynb/paramsweep2-transitions.html#Transition-plots).
> 
> We are looking to add an enhancement where one can pass lists of tuples as arguments `initial` and/or `final`, with **specific** state labels that represent initial and final transition end-points of transitions that should be plotted. So for example calling:
> 
> ```
>     sweep.plot_transitions(initial=[(1,2,4), (1,3,1)], final=[(0,1,0)])
> ```
> 
> should lead to (only) transitions between levels with labels (1,2,4)<->(0,1,0) and (1,3,1)<->(0,1,0) being plotted.
> 
> These changes should not break current code and should be documented in the method's docstring.
> 
> (It would of course be great if this addition would be also briefly explained in the [documentation](https://github.com/scqubits/scqubits-doc) - but that is not part of the bounty).

I was able to get the graph working for a list of initial and final however, 
I am getting error when I try to recreate the above example where initial= [(1,2,4), (1,3,1)], final=[(0,1,0)]
Error:
<img width="821" alt="image" src="https://github.com/scqubits/scqubits/assets/54374648/9f5ffc68-7a64-4b9d-b5db-c5b9bf0ae418">
Reason being initial_energies being nan for initial state of (1,2,4)

While the below works 
```sweep["ng":0.0].plot_transitions(initial=[(1,0,0),(0,0,0)],final=[(1,1,0)])```
<img width="716" alt="image" src="https://github.com/scqubits/scqubits/assets/54374648/ea09e825-70f9-447d-9013-d4ebc98eca10">
<img width="671" alt="image" src="https://github.com/scqubits/scqubits/assets/54374648/282ff690-3fc7-4cc3-a400-a2a0b432bd75">

Also when I remove the 
```["ng":0.0]``` I am met with the following error, is it coore
<img width="807" alt="image" src="https://github.com/scqubits/scqubits/assets/54374648/685e15d9-cb6c-44b2-b56f-6eb7623d64f8">

**Comment by petergthatsme** [comment]
Thanks for taking a stab at this @anushkrishnav 

Maybe you can check in a version of the code with your changes (to a forked repo, say), and add the notebook you're writing to test this - and I can take a closer look. 

It is indeed true that some of the labels will be essentially undefined; it just means that there isn't a single bare state that is a "close enough" match with a large enough overlap. I'm not sure if this is the issue here, or it's something else... but if you check in your code, i can try to take a quick look.

**Comment by anushkrishnav** [comment]
Pushing the notebook on a PR here, can delete it or force merge later ?

**Comment by anushkrishnav** [comment]
@petergthatsme I have created a PR, can you please check I would love to get this  issue done by 12 th

**Comment by petergthatsme** [comment]
thanks. I will try to take a closer look tonight.

**Comment by anushkrishnav** [comment]
> thanks. I will try to take a closer look tonight.

Awesome let me know I am available for the next 12 hrs to work on this

**Comment by petergthatsme** [comment]
sorry for the slow response - busy day. 
I had a quick chance to look at your comments above. 

>Reason being initial_energies being nan for initial state of (1,2,4)

In the worksheet i see that dim for the last subsystem is set to 4... so that would make a state labeled (1,2,4) invalid; i.e. one could at most have three photons resulting in (x,y,3). So maybe that's the problem. 

A somewhat related issue; in an arbitrary Hilbertspace objects, some of the bare_labels will be undefined as some states may just be too hybradized. The code should ideally handle those cases gracefully; i.e. not crash... (if that's the only state provided for either initial or final, maybe even spit out the warning?).. not sure if we're currently handling all the corner cases gracefully though. 

> Also when I remove the ["ng":0.0] I am met with the following error, is it coore

well.. this makes sense.. the scan is over two variables, so by removing that, you're not fixing either of them.. hence the plots would have to be 3d - not something we support here.. (although make a nicer error message could be nice ;)

**Comment by anushkrishnav** [comment]
> In the worksheet i see that dim for the last subsystem is set to 4... so that would make a state labeled (1,2,4) invalid; i.e. one could at most have three photons in the last subsystem resulting in (x,y,3). So maybe that's the problem.

Got it so I will try to check the code with (x,y,3) maybe also throw an error back to user if they attempt what I did ? gives them a straightforward reason why something like (1,2,4) might not work ?

**Comment by petergthatsme** [comment]
right.... it would indeed be good to maybe have some sanity checking code at the beginning of the method that will check all the input; i.e. are all the provided states (initial or final) in the right ranges.

**Comment by anushkrishnav** [comment]
I am currently working on this do you have any example code to test the plot transition with initial and final ?

**Comment by petergthatsme** [comment]
well you could just use the code you already have in the notebook, but just try passing some invalid initial/final states (e.g. out of range levels, bad formatting, etc).

**Comment by anushkrishnav** [comment]
Just to confirm, the current task in hand is to handle wrong inputs, did you get a chance to test if the plot works for valid inputs on initial and final? 
Also what would be a valid initial final tuple ? it would nice to get a few example to check if plot works well

**Comment by anushkrishnav** [comment]
> well.. this makes sense.. the scan is over two variables, so by removing that, you're not fixing either of them.. hence the plots would have to be 3d - not something we support here.. (although showing a nicer error message could be nice ;)

The warning for this is already being raised 
```
File ~/Documents/scqubits/scqubits/core/param_sweep.py:748, in ParameterSweepBase.plot_transitions(self, subsystems, initial, final, sidebands, photon_number, make_positive, coloring, param_indices, **kwargs)
    [746](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:746) param_indices = param_indices or self._current_param_indices
    [747](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:747) if not self._slice_is_1d_sweep(param_indices):
--> [748](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:748)     raise ValueError(
    [749](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:749)         "Transition plots are only supported for a sweep over a "
    [750](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:750)         "single parameter. You can reduce a multi-dimensional "
    [751](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:751)         "sweep by pre-slicing, e.g.,  <ParameterSweep>[0, :, "
    [752](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:752)         "0].plot_transitions(...)"
    [753](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:753)     )
    [754](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:754) specdata_for_highlighting = self.transitions(
    [755](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:755)         subsystems=subsystems,
    [756](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:756)         initial=initial,
   (...)
    [762](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:762)         param_indices=param_indices,
    [763](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:763)     )
    [766](https://file+.vscode-resource.vscode-cdn.net/Users/anushkrishnav/Documents/scqubits/~/Documents/scqubits/scqubits/core/param_sweep.py:766) specdata_all = copy.deepcopy(self[param_indices].dressed_specdata)

ValueError: Transition plots are only supported for a sweep over a single parameter. You can reduce a multi-dimensional sweep by pre-slicing, e.g.,  <ParameterSweep>[0, :, 0].plot_transitions(...)
```

**Comment by petergthatsme** [comment]
well.. if you can get some sanity checks in place that would be good. 
Valid inputs include initial and final states that are in-range. So say, you have a two-subystem Hilbert space of dimensions (3,5). Valid states include those where the first index varies between 0 and 2 and second between 0 and 4. 
i haven't not had a chance to extensively test your code yet.

**Comment by anushkrishnav** [comment]
Sounds good, I will put some checks and request a review on the code
