### ISSUE TITLE
[Other issue]

### ISSUE THREAD

**Issue by edumur** [scqubits/scqubits#239]
Dear all,

When I am making custom circuit with scqubits I noticed that as soon as an inductance is put into the circuit, the cutoff parameter has to be large in order to get correct eigenenergies.
For instance, with the following fluxonium:
```python
import numpy as np
import matplotlib.pyplot as plt
import scqubits as scq
from tqdm import tqdm
%matplotlib ipympl

zp_yaml = """
- [JJ, 0, 1, EJ1=100, ECJ1=1]
- [JJ, 0, 1, EJ2=100, ECJ2=1]
- [L, 0, 1, El2=0.400]
"""
circuit = scq.Circuit(
    zp_yaml, from_file=False, ext_basis="discretized", generate_noise_methods=True
)

fs = np.concatenate((np.linspace(0, 0.49, 100)[:-1],
                      np.linspace(0.49, 0.51, 500)))

circuit.cutoff_ext_1 = 30
spectrum30 = circuit.get_spectrum_vs_paramvals('Φ1', fs, num_cpus=8)
circuit.cutoff_ext_1 = 60
spectrum60 = circuit.get_spectrum_vs_paramvals('Φ1', fs, num_cpus=8)
circuit.cutoff_ext_1 = 90
spectrum90 = circuit.get_spectrum_vs_paramvals('Φ1', fs, num_cpus=8)
circuit.cutoff_ext_1 = 120
spectrum120 = circuit.get_spectrum_vs_paramvals('Φ1', fs, num_cpus=8)

fig, ax = plt.subplots(1, 4, figsize=(9,6), sharey=True)
ax[0].plot(fs, spectrum30.energy_table[:,1]-spectrum30.energy_table[:,0], label='30')
ax[0].plot(fs, spectrum30.energy_table[:,2]-spectrum30.energy_table[:,0], label='30')
ax[0].plot(fs, spectrum30.energy_table[:,3]-spectrum30.energy_table[:,0], label='30')

ax[1].plot(fs, spectrum60.energy_table[:,1]-spectrum60.energy_table[:,0], label='60')
ax[1].plot(fs, spectrum60.energy_table[:,2]-spectrum60.energy_table[:,0], label='60')
ax[1].plot(fs, spectrum60.energy_table[:,3]-spectrum60.energy_table[:,0], label='60')

ax[2].plot(fs, spectrum90.energy_table[:,1]-spectrum90.energy_table[:,0], label='90')
ax[2].plot(fs, spectrum90.energy_table[:,2]-spectrum90.energy_table[:,0], label='90')
ax[2].plot(fs, spectrum90.energy_table[:,3]-spectrum90.energy_table[:,0], label='90')

ax[3].plot(fs, spectrum120.energy_table[:,1]-spectrum120.energy_table[:,0], label='120')
ax[3].plot(fs, spectrum120.energy_table[:,2]-spectrum120.energy_table[:,0], label='120')
ax[3].plot(fs, spectrum120.energy_table[:,3]-spectrum120.energy_table[:,0], label='120')

ax[0].set_ylabel('Transition (GHz)')
for i in fig.get_axes():
    i.set_xlabel('flux (phi_0)')
fig.suptitle('cutoff')
ax[0].set_title('30')
ax[1].set_title('60')
ax[2].set_title('90')
ax[3].set_title('120')
```

Where I got:
![image](https://github.com/user-attachments/assets/cff340f7-aa04-466a-bf36-1c1ac57f1c81)

Is this expected? If so why?

Thanks a lot.

**Comment by petergthatsme** [comment]
This would seem reasonable to me... 
Some super heuristic "explanation" might be something along the lines of: the EJ of your junctions is very "high", charging energy "low"... and inductive energy "low".. so your potential landscape is a "wide parabola", with many "tall" cosine peaks... the low EC means that your (low lying) wavefunctions live deep inside those wells, and thus they span over multiple ones...  
All this means that you need a substantially large basis count (here scqubits chooses discretized phi basis) to capture this evecs structure properly. 

You could try plotting the wavefunctions to get a better sense of what things look like.

**Comment by ZhaoTianPu** [comment]
In addition to @petergthatsme ‘s comment, to guarantee convergence you may also need to check if increasing phi grid range affect your eigenenergies. This document page instructs how to change the grid range: https://scqubits.readthedocs.io/en/v4.1/guide/circuit/ipynb/custom_circuit_bases.html

Another alternative choice is to use the harmonic oscillator basis (as we did in the Fluxonium class). This way you only need to increase the number of basis states to check for convergence.

The physics of adding just a small shunting inductor to a transmon circuit (this parameter regime is known as the Blochnium regime) makes its physics quite different from transmon. Some relevant papers about such parameter regime (and hopefully can help explain why the requirements on basis for convergence is more demanding):
https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.103.217004
https://www.nature.com/articles/s41586-020-2687-9

**Comment by edumur** [comment]
thanks a lot!
