### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dkweiss31** [scqubits/scqubits#243]
Hello friends! I'm trying to release a package that depends on scqubits and I'm seeing test failures relating to deprecation of np.complex_ in scqubits. I see that this is fixed on the master branch but the most recent release is from before this patch. I'm hoping there can be a new release including these fixes? Thanks!

**Comment by petergthatsme** [comment]
Yes, Danny the numpy 2.0 compatibility has been sorted for a while now, but it's in `main` and not released yet. 
We are very close to making a new release, just trying to finalize some pesky prefactor that's wrong in one of the noise channels calculations. I will keep you in the loop as as soon as we release.

**Comment by petergthatsme** [comment]
hey @dkweiss31 we finally released a new version. Will close this.
