### ISSUE TITLE
[Suggestion/request] Documentation for higher harmonics

### ISSUE THREAD

**Issue by dkweiss31** [scqubits/scqubits#250]
So it seems based on the changelog for version 4.2 and the below code that there is new support for playing with higher harmonics in custom circuits. This is a wonderful addition, thank you! I have not however been able to find any documentation, user guide, docstring etc. documenting this change or providing examples for how one might initialize a custom circuit including a junction for higher harmonics and what sort of "grammar" is supported. I'm hoping this can be added?

https://github.com/scqubits/scqubits/blob/main/scqubits/core/circuit_utils.py#L37-L60

**Comment by saipavanc** [comment]
Hi Danny, thanks for reminding me about the documentation for higher harmonics. I will describe this in the documentation, and push the commit shortly. I did discuss this earlier in issue #231, which gives a basic gist if you want to get started before then.

**Comment by dkweiss31** [comment]
Nice, that's exactly what I was looking for. Thanks Sai!

**Comment by saipavanc** [comment]
You are welcome! I am very glad you found this useful!
