### ISSUE TITLE
In FullZeroPi, directly setting parameters after initialization, can make internal state of object inconsistent

### ISSUE THREAD

**Issue by petergthatsme** [scqubits/scqubits#47]
For example doing `full_zero_pi.EJ=xx` will not update `full_zero_pi._zero_pi.EJ`, and will lead to wrong (unexpected) results.

One way to go around the problem would be to set relevant FullZeroPi variables as properties, and just point them to the _zero_pi object.

**Comment by jkochNU** [comment]
This is fixed in the v1.1 release.
