### ISSUE TITLE
[Suggestion/request] Coherence functions for the different qubits

### ISSUE THREAD

**Issue by pranavm1502** [scqubits/scqubits#50]
Firstly, this is a great library for exploring parameter regimes/ connectivity in different SC qubit architectures! It appears to me that functions for calculating coherence properties are lacking.

For example, including the calculation of T_phi following @petergthatsme 's work on ZP [paper](https://iopscience.iop.org/article/10.1088/1367-2630/aab7cd/meta) would be very useful for users.

**Comment by jkochNU** [comment]
Thanks, Pranav - I agree. Peter and I talked about this already, and it’s on our to-do list.

**Comment by petergthatsme** [comment]
I'm closing this as the core noise functionality has been implemented in version 1.3 (and more predefined noise channels will be still added in the near future, especially for the more complex qubits like the zeropi and other upcoming ones) .
