### ISSUE TITLE
Plotting spectra using ParameterSweep

### ISSUE THREAD

**Issue by dkweiss31** [scqubits/scqubits#51]
If I create a `ParameterSweep` object and plot the spectrum using `dressed_spectrum` from `sweep_plotting.py`, the spectrum is generated correctly. However If I attempt to impose my own `ylim` values using say `dress_spectrum(sweep, ylim=(4,5))`, the minimum y value is correctly taken into account, however the maximum y value is ignored, and the figure still plots all the way up to the maximum eigenvalue generated by the `ParameterSweep` object.

**Comment by jkochNU** [comment]
Thanks for catching this. This is fixed with https://github.com/scqubits/scqubits/commit/c0463fc879c64b47cdbc0fe306a5e8b452aa04aa
