### ISSUE TITLE
Plotting with linestyles

### ISSUE THREAD

**Issue by dkweiss31** [scqubits/scqubits#53]
I would like to plot a spectrum with dashed lines, to compare with a solid line spectrum. The code
`FluxQubit.plot_evals_vs_paramvals('flux', flux_list, evals_count=4, subtract_ground=False, linestyle='--')` produces the error 
AttributeError: 'AxesSubplot' object has no attribute 'set_linestyle'.

**Comment by jkochNU** [comment]
This behavior is consistent with the options scqubits currently supports, I believe:
![9356A54F-E7A7-4427-A5D5-0B0F3B2EC7A0](https://user-images.githubusercontent.com/19193849/74073544-4fdb0380-49d0-11ea-8ecf-d0e6d9185280.jpeg)

We may look into extending that in the future. Note: all plot routines return the Axes and Figure objects which can be further modified on the user side.

**Comment by jkochNU** [comment]
While it would be feasible to have linestyle/linewidth options be handled explicitly with `_process_options` and then routed to `plot`, this solution is not scalable (there could be many more option support requests in the future).

**Comment by petergthatsme** [comment]
I added 'alpha', 'linestyle', 'linewidth', 'marker', 'markersize' options to all the standard x vs y plotting routines. And 'interpolation' to ones that use `imshow`.
Let me know if we need any other obvious ones that would be useful for people. 
The changes are in master now, so should make it to next release.
