### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by faridhassani** [scqubits/scqubits#56]
Hey everyone,

I was trying the new features of the Scqubits library, specifically explorer, which I happen to stuck with an error occurring while the function tries to calculate dispersive shifts. The error I get is "Key Error: chi_osc1_qbt0" and python traces it back to "sweep.sweep_data[data_key]" function. Please tell me if I'm simply missing something. Here is how I get to the error (in here I basically follow the example 1 the fluxonium coupled to resonator):

`
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

import matplotlib.pyplot as plt
import numpy as np
import scqubits.utils.sweep_plotting as splot

import scqubits as qubit
from scqubits import HilbertSpace, InteractionTerm, ParameterSweep, Explorer

qbt = qubit.Fluxonium(
    EJ=35,
    EC=0.14,
    EL=35,
    flux=0.0,
    cutoff=110,
    truncated_dim=9
)

osc = qubit.Oscillator(
    E_osc=9.05,
    truncated_dim=5
)

hilbertspace = qubit.HilbertSpace([qbt, osc])

interaction = InteractionTerm(
    g_strength=0.2,
    hilbertspace = hilbertspace,
    op1=qbt.n_operator(),
    subsys1=qbt,
    op2=osc.creation_operator() + osc.annihilation_operator(),
    subsys2=osc
)

interaction_list = [interaction]
hilbertspace.interaction_list = interaction_list

param_name = '$\Phi_{ext}/\Phi_0$'
param_vals = np.linspace(-0.5, 1.5, 500)

subsys_update_list = [qbt]

def update_hilbertspace(param_val):
    qbt.flux = param_val

sweep = ParameterSweep(
    param_name=param_name,
    param_vals=param_vals,
    evals_count=10,
    hilbertspace=hilbertspace,
    subsys_update_list=subsys_update_list,
    update_hilbertspace=update_hilbertspace
)

#explorer fail to calculate the "chi". The error is "KeyError: 'chi_osc1_qbt0'".

explorer = Explorer(
    sweep=sweep,
    evals_count=10
)
explorer.interact()`

**Comment by jkochNU** [comment]
@petergthatsme I believe this is fixed in the current master already (need to double check). If so, we could consider pushing another release, though I can wait if you'd like to include the noise code as well.

@faridhassani You can try to check out either master or jk-devel from github, if you need a solution very quickly.

**Comment by petergthatsme** [comment]
@jkochNU i would probably say let's just release your latest changes, and maybe do another release once the noise stuff is there. There has been lots of under-the-hood stuff that's recently changed, so maybe even better this way.

**Comment by jkochNU** [comment]
This should be fixed with the new release of v1.2 that we just pushed to PyPi and conda-forge. @faridhassani Please confirm, so I know whether I can close this issue.

**Comment by faridhassani** [comment]
Its fixed (^_^). Thanks.

**Comment by jkochNU** [comment]
Excellent, closing this as resolved.
