### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by faridhassani** [scqubits/scqubits#57]
Hello again,

While I was working with the example 1: fluxonium coupled to resonator, I noticed a tiny mistake in the online documents/ user guide/ explorer/ example 1(fluxonium coupled to resonator)/ HilbertSpace setup. In the code sample for "interactionterm" function, the hilbertspace argument is missing. I attached a photo with more indication for reference.

Cheers,
Farid.
![tiny_bug](https://user-images.githubusercontent.com/61017451/74456190-b8b9f400-4e86-11ea-8c1e-1c480ff80519.jpg)

**Comment by jkochNU** [comment]
The documentation is indeed one step ahead of the released code in this case. On the current master (release soonish), the HilbertSpace reference in InteractionTerm is removed to avoid circular referencing. Once released, old code will still work but produce a deprecation warning.

**Comment by jkochNU** [comment]
Fixed with release of v1.2
