### ISSUE TITLE
Changes between conda/pip version and git master

### ISSUE THREAD

**Issue by notaqubit** [scqubits/scqubits#61]
Hey! 

Great package! Glad to see this online and excited to start playing around with the examples.

I tried installing it yesterday several times (both with conda and pip) and couldn't get it to past the testing script. After digging around a bit, I noticed that there were quite a few differences between the downloaded version and git master. This included: 

(qutip-env) UNAME@macbook scqubits % diff ../scqubits /Users/UNAME/Documents/scqubits-master/scqubits -q
Files ../scqubits/__init__.py and /Users/UNAME/Documents/scqubits-master/scqubits/__init__.py differ
Only in ../scqubits: __pycache__
Common subdirectories: ../scqubits/core and /Users/UNAME/Documents/scqubits-master/scqubits/core
Files ../scqubits/settings.py and /Users/UNAME/Documents/scqubits-master/scqubits/settings.py differ
Common subdirectories: ../scqubits/tests and /Users/UNAME/Documents/scqubits-master/scqubits/tests

Common subdirectories: ../scqubits/utils and /Users/UNAME/Documents/scqubits-master/scqubits/utils

I tried manually resolving this (w/o git) by adding the missing files but couldn't get rid of all the failures. After several runs, managed to get 7 failures / 44 passes. Looks like the missing hilbertspace arg in InteractionTerm was the source of all the remaining failures. 

Any suggestions?  I noticed you just updated the package. Maybe I should just reinstall scqubits with the new master branch and re-run the test? Thanks!

Setup:
macOS Catalina V 10.15.3
scqubits V 1.1.1
Python 3.7.6
pip 20.0.02
conda 4.8.2

**Comment by jkochNU** [comment]
Thanks for posting this here. Master and pip/conda were indeed quite different until last night when v1.2 was released. (That should not be the source of the problem.)
What may be happening: pytest reads reference data from disk and tests writing calculated data to disk. For that, the corresponding directories have to exist. I have a suspicion that the packaging may have gotten rid of those directories which will make a large number of tests fail. This problem would exist both for v1.1.1 and v1.2. (The tests we run prior to releasing are run by cloning the github repository, so we would miss this issue.)

This would mean that the testing suite is broken, but not the package itself.
Are you able to run any of the example jupyter notebooks?

**Comment by jkochNU** [comment]
Confirmed: test suite is broken when installing through pip or conda, both v1.1.1 and v1.2. Cursory glance shows a bunch of OSErrors 'No such file or directory', consistent with packages missing the test data directory.

**Comment by jkochNU** [comment]
This should be fixed with https://github.com/scqubits/scqubits/commit/920f8bc1c97819badd1327eb8b4dded4ee98d237 and the release of v1.2.1.

**Comment by notaqubit** [comment]
Just ran the test again. Nothing failed but it did skip a few things: 
-TestFluxonium::test_plot_potential
-TestTransmon::test_plot_potential
Looks like I'm in the clear for now. Thanks for the help!

**Comment by jkochNU** [comment]
No problem! (The skips you are seeing are expected behavior.)
