### ISSUE TITLE
variable annotations not supported in python 3.5; scqubits fails to import

### ISSUE THREAD

**Issue by petergthatsme** [scqubits/scqubits#62]
scqubits fails in python 3.5 (which we officially support at the moment), as variable annotations are not supported (they only became a thing in 3.6). For example in constants.py we have:
```
_HAS_H5PY: bool
_HAS_JSON: bool
_HAS_IPYTHON: bool
_HAS_IPYWIDGETS: bool
```
we could either enforce that we require version >3.6, or rewrite these. 
Thoughts?

**Comment by jkochNU** [comment]
3.6+  specific code used in scqubits is not limited to annotations, but also includes usage of `__set_name__`. Going forward, we are supporting Python versions >=3.6. This is now correctly reflected in the updated documentation. (We may reconsider refactoring if there is significant demand from the user base for Python 3.5 support.)
