### ISSUE TITLE
[Suggestion/request]

### ISSUE THREAD

**Issue by jkochNU** [scqubits/scqubits#65]
Update documentation for disordered zero-pi qubit (missing disorder parameters, for example).

**Comment by jkochNU** [comment]
@PhilippAumann When you get a chance, please take a look at the docs and let me know whether changes address the issue. I only realized late that the situation was worse than I thought. Should be much better now.

**Comment by jkochNU** [comment]
Fixed with https://github.com/scqubits/scqubits/commit/f203deb06435dc177e80bffc799fc9381dfd324f

**Comment by PhilippAumann** [comment]
Thanks for fixing it!
