### ISSUE TITLE
Units of flux variable in Fluxonium [Bug report]

### ISSUE THREAD

**Issue by PhilippAumann** [scqubits/scqubits#71]
The documentation for the fluxonium class states that, 

> Here, flux is given in dimensionless units, in the form 2\pi\Phi_\text{ext}/\Phi_0

However, the 2*pi are hard-wired into the implementation of the operators. 
If I am not mistaken, this means, that flux should be given in Units of $Phi_\text{ext}/\Phi_0 $(without the 2*pi). At least for my implementation I had to divide the flux by 2*pi in order to show the expected results. 
Maybe I am just confused, since my definition differs by a factor of 2*pi from the definition used in scqubits, but I still think one should have a look at it.

**Comment by jkochNU** [comment]
Indeed, that factor 2pi was incorrect in the documentation. This should be fixed now (and reflected on RTD). I found and took care of two additional occurrences in the documentation for the two zero-pi classes.
