### ISSUE TITLE
Disorder Hamiltonian in FullZeroPi is non-Hermitian

### ISSUE THREAD

**Issue by xyyou2015** [scqubits/scqubits#73]
The disorder term in the FullZeroPi Hamiltonian is non-Hermitian. The disorder term should be 
\sum_{l,l'} (g_{l,l'} | l \rangle \langle l'| a + h.c.). However, the implementation is instead \sum_{l,l'} g_{l,l'} | l \rangle \langle l'| (a + a^\dag). 
If dC=0, the current implementation is fine, but in general, when dC!=0, this should be fixed. 
<img width="742" alt="image" src="https://user-images.githubusercontent.com/32179442/83562302-f3e83d80-a4de-11ea-94eb-6ae5a01e7732.png">

**Comment by jkochNU** [comment]
Fixed with ea57413 and 90ca57d .
