### ISSUE TITLE
more general InteractionTerm form

### ISSUE THREAD

**Issue by petergthatsme** [scqubits/scqubits#76]
It would be useful if we supported a more general InteractionTerm format. So for example, something like `cos(phi1 - phi2 + phix)`. At the moment one has to expend this out and build multiple InteractionTerms manually... maybe one way to do it, would be to allow the user to provide a general function that would take phi1 and phi2, and at the moment of building the interaction H would do the right thing with interaction_wrap, and hence generating the correct thing.

**Comment by jkochNU** [comment]
Note that this enhancement will likely require follow-up changes for HilbertSpace ipywidget interface

**Comment by jkochNU** [comment]
@petergthatsme I believe this is addressed by the v2 release. Please confirm & close if appropriate.
