### ISSUE TITLE
[Bug report] Image Failure for Zero pi

### ISSUE THREAD

**Issue by 99elam** [scqubits/scqubits#84]
**Describe the bug**
When running through the Jupyter notebook example for Zero pi, the images did not show up. The exact error was "FileNotFoundError: [Errno 2] No such file or directory: '/srv/conda/envs/notebook/lib/python3.7/site-packages/scqubits/core/qubit_img/zeropi.jpg'"

**Expected behavior**
I expected the image to show up.

**To Reproduce**
Run through each cell of the Zero Pi example notebook. 

**OS and version used (please complete the following information):**
 - OS: Windows
 - scqubits version [e.g., 1.1]: 1.3
 - Python version: 3.7

**Comment by jkochNU** [comment]
This indicates that image files were not properly packaged to become part of the library for the releases on PyPi / conda-forge.
The culprit is a missing update in `MANIFEST.in`, I believe. 
Need to replace `graft scqubits/core/qubit_pngs` with `graft scqubits/core/qubit_img`.

**Comment by jkochNU** [comment]
Resolved in v1.3.2
