### ISSUE TITLE
Cannot provide custom scaling for wavefunctions[Bug report]

### ISSUE THREAD

**Issue by dkweiss31** [scqubits/scqubits#85]
Providing a custom scaling for wavefunctions has no effect.

'''
tran = qubit.Transmon.create()
tran.plot_phi_wavefunction(mode='real', which=[0, 1, 2, 3], scaling=2.0)
'''
or 
'''
tran.plot_phi_wavefunction(mode='real', which=[0, 1, 2, 3], scaling=1.0)
'''
have the same effect.

**Comment by jkochNU** [comment]
Overhauled scaling of wavefunctions in `QubitBaseClass1d.plot_wavefunction(...)`. Should also address #85, @dkweiss31  - please confirm.

**Comment by dkweiss31** [comment]
Fixed by c4fd387c8d01482405c9c62e2692c35908c3b99d
