### ISSUE TITLE
Qubit resonator coupling inaccuracy  [Bug report]

### ISSUE THREAD

**Issue by faridhassani** [scqubits/scqubits#87]
Hi,

I'm working with the tunable transmon library on scqubits and I notice when I sweep the flux parameter the splitting between the resonator and first transition "ge" of the qubit is more than "2g", where the "g" is the coupling strength defined in the interaction term. For example for a qubit with Ejmax=58GHz , Ec=0.38GHz coupled to a resonator Wr=10.4GHz with a coupling strength of g=0.344 GHz, I see a splitting of about 900MHz which is more than what I should get. I thought maybe the accuracy of the simulation in not good enough and I tried the simulation with "ngcut=200" and "truncated_dim=50" and got the same result. Am I missing something here or could be that I'm somehow making the interaction wrong? I will attach the code here.

Thank you so much for your help and support,
Farid.

[tunable transmon PBB.zip](https://github.com/scqubits/scqubits/files/5438642/tunable.transmon.PBB.zip)

**Comment by jkochNU** [comment]
@faridhassani In your expectation for the splitting, are you taking into account that the "g" you are defining does not include the value of the matrix elements of the charge operator? Comparing with https://journals.aps.org/pra/pdf/10.1103/PhysRevA.76.042319 Eq. (3.2) and (3.3). Your "g" might not be the "g" there (as the latter absorbs the charge matrix elements, and it looks like you do not).

**Comment by faridhassani** [comment]
Hi Jens,

I see how I was confused, just calculated including the charge matrix element and the issue is resolved. Thank you for the quick response.

best,
Farid.
